x64:
    remap "__imp_ProcessPrngGuid" "__imp_bcryptprimitives$ProcessPrngGuid"
    remap "__imp_ProcessPrng" "__imp_bcryptprimitives$ProcessPrng"
    remap "__imp_MSCryptConvertRsaPrivateBlobToFullRsaBlob" "__imp_bcryptprimitives$MSCryptConvertRsaPrivateBlobToFullRsaBlob"
    remap "__imp_GetSignatureInterface" "__imp_bcryptprimitives$GetSignatureInterface"
    remap "__imp_GetSecretAgreementInterface" "__imp_bcryptprimitives$GetSecretAgreementInterface"
    remap "__imp_GetRngInterface" "__imp_bcryptprimitives$GetRngInterface"
    remap "__imp_GetKeyDerivationInterface" "__imp_bcryptprimitives$GetKeyDerivationInterface"
    remap "__imp_GetHashInterface" "__imp_bcryptprimitives$GetHashInterface"
    remap "__imp_GetCipherInterface" "__imp_bcryptprimitives$GetCipherInterface"
    remap "__imp_GetAsymmetricEncryptionInterface" "__imp_bcryptprimitives$GetAsymmetricEncryptionInterface"
x86:
    remap "__imp__ProcessPrngGuid@4" "__imp__bcryptprimitives$ProcessPrngGuid@4"
    remap "__imp__ProcessPrng@8" "__imp__bcryptprimitives$ProcessPrng@8"
    remap "__imp__MSCryptConvertRsaPrivateBlobToFullRsaBlob@20" "__imp__bcryptprimitives$MSCryptConvertRsaPrivateBlobToFullRsaBlob@20"
    remap "__imp__GetSignatureInterface@16" "__imp__bcryptprimitives$GetSignatureInterface@16"
    remap "__imp__GetSecretAgreementInterface@16" "__imp__bcryptprimitives$GetSecretAgreementInterface@16"
    remap "__imp__GetRngInterface@12" "__imp__bcryptprimitives$GetRngInterface@12"
    remap "__imp__GetKeyDerivationInterface@16" "__imp__bcryptprimitives$GetKeyDerivationInterface@16"
    remap "__imp__GetHashInterface@16" "__imp__bcryptprimitives$GetHashInterface@16"
    remap "__imp__GetCipherInterface@16" "__imp__bcryptprimitives$GetCipherInterface@16"
    remap "__imp__GetAsymmetricEncryptionInterface@16" "__imp__bcryptprimitives$GetAsymmetricEncryptionInterface@16"
