x64:
    remap "__imp_ImportRSoPData" "__imp_gpedit$ImportRSoPData"
    remap "__imp_ExportRSoPData" "__imp_gpedit$ExportRSoPData"
    remap "__imp_DllUnregisterServer" "__imp_gpedit$DllUnregisterServer"
    remap "__imp_DllRegisterServer" "__imp_gpedit$DllRegisterServer"
    remap "__imp_DllGetClassObject" "__imp_gpedit$DllGetClassObject"
    remap "__imp_DllCanUnloadNow" "__imp_gpedit$DllCanUnloadNow"
    remap "__imp_DeleteGPOLink" "__imp_gpedit$DeleteGPOLink"
    remap "__imp_DeleteAllGPOLinks" "__imp_gpedit$DeleteAllGPOLinks"
    remap "__imp_CreateGPOLink" "__imp_gpedit$CreateGPOLink"
    remap "__imp_BrowseForGPO" "__imp_gpedit$BrowseForGPO"
x86:
    remap "__imp__ord_104@12" "__imp__gpedit$ord_104@12"
    remap "__imp__ord_103@12" "__imp__gpedit$ord_103@12"
    remap "__imp__ord_102" "__imp__gpedit$ord_102"
    remap "__imp__ord_101@4" "__imp__gpedit$ord_101@4"
    remap "__imp__ord_100@8" "__imp__gpedit$ord_100@8"
    remap "__imp__ImportRSoPData@8" "__imp__gpedit$ImportRSoPData@8"
    remap "__imp__ExportRSoPData@8" "__imp__gpedit$ExportRSoPData@8"
    remap "__imp__DllGetClassObject@12" "__imp__gpedit$DllGetClassObject@12"
    remap "__imp__DllCanUnloadNow" "__imp__gpedit$DllCanUnloadNow"
    remap "__imp__DeleteGPOLink@8" "__imp__gpedit$DeleteGPOLink@8"
    remap "__imp__DeleteAllGPOLinks@4" "__imp__gpedit$DeleteAllGPOLinks@4"
    remap "__imp__CreateGPOLink@12" "__imp__gpedit$CreateGPOLink@12"
    remap "__imp__BrowseForGPO@8" "__imp__gpedit$BrowseForGPO@8"
