x64:
    remap "__imp_IASVariantChangeType" "__imp_iassvcs$IASVariantChangeType"
    remap "__imp_IASUninitialize" "__imp_iassvcs$IASUninitialize"
    remap "__imp_IASShutdown" "__imp_iassvcs$IASShutdown"
    remap "__imp_IASSetMaxThreadIdle" "__imp_iassvcs$IASSetMaxThreadIdle"
    remap "__imp_IASSetMaxNumberOfThreads" "__imp_iassvcs$IASSetMaxNumberOfThreads"
    remap "__imp_IASRequestThread" "__imp_iassvcs$IASRequestThread"
    remap "__imp_IASReportSecurityEvent" "__imp_iassvcs$IASReportSecurityEvent"
    remap "__imp_IASReportLicenseViolation" "__imp_iassvcs$IASReportLicenseViolation"
    remap "__imp_IASReportEvent" "__imp_iassvcs$IASReportEvent"
    remap "__imp_IASRegisterComponent" "__imp_iassvcs$IASRegisterComponent"
    remap "__imp_IASRadiusCrypt" "__imp_iassvcs$IASRadiusCrypt"
    remap "__imp_IASInitialize" "__imp_iassvcs$IASInitialize"
    remap "__imp_IASGlobalUnlock" "__imp_iassvcs$IASGlobalUnlock"
    remap "__imp_IASGlobalLock" "__imp_iassvcs$IASGlobalLock"
    remap "__imp_IASGetProductLimits" "__imp_iassvcs$IASGetProductLimits"
    remap "__imp_IASGetLocalDictionary" "__imp_iassvcs$IASGetLocalDictionary"
    remap "__imp_IASGetHostByName" "__imp_iassvcs$IASGetHostByName"
    remap "__imp_IASGetDictionary" "__imp_iassvcs$IASGetDictionary"
    remap "__imp_IASAllocateUniqueID" "__imp_iassvcs$IASAllocateUniqueID"
    remap "__imp_IASAdler32" "__imp_iassvcs$IASAdler32"
x86:
