x64:
    remap "__imp_SnmpMgrTrapListen" "__imp_mgmtapi$SnmpMgrTrapListen"
    remap "__imp_SnmpMgrStrToOid" "__imp_mgmtapi$SnmpMgrStrToOid"
    remap "__imp_SnmpMgrRequest" "__imp_mgmtapi$SnmpMgrRequest"
    remap "__imp_SnmpMgrOpen" "__imp_mgmtapi$SnmpMgrOpen"
    remap "__imp_SnmpMgrOidToStr" "__imp_mgmtapi$SnmpMgrOidToStr"
    remap "__imp_SnmpMgrGetTrapEx" "__imp_mgmtapi$SnmpMgrGetTrapEx"
    remap "__imp_SnmpMgrGetTrap" "__imp_mgmtapi$SnmpMgrGetTrap"
    remap "__imp_SnmpMgrCtl" "__imp_mgmtapi$SnmpMgrCtl"
    remap "__imp_SnmpMgrClose" "__imp_mgmtapi$SnmpMgrClose"
x86:
    remap "__imp__serverTrapThread@4" "__imp__mgmtapi$serverTrapThread@4"
    remap "__imp__SnmpMgrTrapListen@4" "__imp__mgmtapi$SnmpMgrTrapListen@4"
    remap "__imp__SnmpMgrStrToOid@8" "__imp__mgmtapi$SnmpMgrStrToOid@8"
    remap "__imp__SnmpMgrRequest@20" "__imp__mgmtapi$SnmpMgrRequest@20"
    remap "__imp__SnmpMgrOpen@16" "__imp__mgmtapi$SnmpMgrOpen@16"
    remap "__imp__SnmpMgrOidToStr@8" "__imp__mgmtapi$SnmpMgrOidToStr@8"
    remap "__imp__SnmpMgrGetTrapEx@32" "__imp__mgmtapi$SnmpMgrGetTrapEx@32"
    remap "__imp__SnmpMgrGetTrap@24" "__imp__mgmtapi$SnmpMgrGetTrap@24"
    remap "__imp__SnmpMgrCtl@28" "__imp__mgmtapi$SnmpMgrCtl@28"
    remap "__imp__SnmpMgrClose@4" "__imp__mgmtapi$SnmpMgrClose@4"
