x64:
    remap "__imp_NlNetlogonMain" "__imp_netlogon$NlNetlogonMain"
    remap "__imp_NetILogonSamLogon" "__imp_netlogon$NetILogonSamLogon"
    remap "__imp_InitSecurityInterfaceW" "__imp_netlogon$InitSecurityInterfaceW"
    remap "__imp_I_NetNotifyTrustedDomain" "__imp_netlogon$I_NetNotifyTrustedDomain"
    remap "__imp_I_NetNotifyRole" "__imp_netlogon$I_NetNotifyRole"
    remap "__imp_I_NetNotifyNtdsDsaDeletion" "__imp_netlogon$I_NetNotifyNtdsDsaDeletion"
    remap "__imp_I_NetNotifyNetlogonDllHandle" "__imp_netlogon$I_NetNotifyNetlogonDllHandle"
    remap "__imp_I_NetNotifyMachineAccount" "__imp_netlogon$I_NetNotifyMachineAccount"
    remap "__imp_I_NetNotifyDsChange" "__imp_netlogon$I_NetNotifyDsChange"
    remap "__imp_I_NetNotifyDelta" "__imp_netlogon$I_NetNotifyDelta"
    remap "__imp_I_NetLogonSetServiceBits" "__imp_netlogon$I_NetLogonSetServiceBits"
    remap "__imp_I_NetLogonSendToSamOnPdc" "__imp_netlogon$I_NetLogonSendToSamOnPdc"
    remap "__imp_I_NetLogonReadChangeLog" "__imp_netlogon$I_NetLogonReadChangeLog"
    remap "__imp_I_NetLogonNewChangeLog" "__imp_netlogon$I_NetLogonNewChangeLog"
    remap "__imp_I_NetLogonMixedDomain" "__imp_netlogon$I_NetLogonMixedDomain"
    remap "__imp_I_NetLogonLdapLookupEx" "__imp_netlogon$I_NetLogonLdapLookupEx"
    remap "__imp_I_NetLogonGetSerialNumber" "__imp_netlogon$I_NetLogonGetSerialNumber"
    remap "__imp_I_NetLogonGetIpAddresses" "__imp_netlogon$I_NetLogonGetIpAddresses"
    remap "__imp_I_NetLogonGetAuthDataEx" "__imp_netlogon$I_NetLogonGetAuthDataEx"
    remap "__imp_I_NetLogonFree" "__imp_netlogon$I_NetLogonFree"
    remap "__imp_I_NetLogonCloseChangeLog" "__imp_netlogon$I_NetLogonCloseChangeLog"
    remap "__imp_I_NetLogonAppendChangeLog" "__imp_netlogon$I_NetLogonAppendChangeLog"
    remap "__imp_I_NetLogonAddressToSiteName" "__imp_netlogon$I_NetLogonAddressToSiteName"
    remap "__imp_I_DsGetDcCache" "__imp_netlogon$I_DsGetDcCache"
    remap "__imp_DsrGetDcNameEx2" "__imp_netlogon$DsrGetDcNameEx2"
x86:
