x64:
    remap "__imp_vServerPropPages" "__imp_printui$vServerPropPages"
    remap "__imp_vQueueCreate" "__imp_printui$vQueueCreate"
    remap "__imp_vPrinterPropPages" "__imp_printui$vPrinterPropPages"
    remap "__imp_vDocumentDefaults" "__imp_printui$vDocumentDefaults"
    remap "__imp_bPrinterSetup" "__imp_printui$bPrinterSetup"
    remap "__imp_bFolderRefresh" "__imp_printui$bFolderRefresh"
    remap "__imp_bFolderGetPrinter" "__imp_printui$bFolderGetPrinter"
    remap "__imp_bFolderEnumPrinters" "__imp_printui$bFolderEnumPrinters"
    remap "__imp_UnregisterPrintNotify" "__imp_printui$UnregisterPrintNotify"
    remap "__imp_ShowErrorMessageSC" "__imp_printui$ShowErrorMessageSC"
    remap "__imp_ShowErrorMessageHR" "__imp_printui$ShowErrorMessageHR"
    remap "__imp_RegisterPrintNotify" "__imp_printui$RegisterPrintNotify"
    remap "__imp_PrinterPropPageProvider" "__imp_printui$PrinterPropPageProvider"
    remap "__imp_PrintUIEntryW" "__imp_printui$PrintUIEntryW"
    remap "__imp_PrintNotifyTray_Init" "__imp_printui$PrintNotifyTray_Init"
    remap "__imp_PrintNotifyTray_Exit" "__imp_printui$PrintNotifyTray_Exit"
    remap "__imp_PnPInterface" "__imp_printui$PnPInterface"
    remap "__imp_GetLegacyPrintUI" "__imp_printui$GetLegacyPrintUI"
    remap "__imp_DocumentPropertiesWrap" "__imp_printui$DocumentPropertiesWrap"
    remap "__imp_DllGetClassObject" "__imp_printui$DllGetClassObject"
    remap "__imp_DllCanUnloadNow" "__imp_printui$DllCanUnloadNow"
    remap "__imp_ConstructPrinterFriendlyName" "__imp_printui$ConstructPrinterFriendlyName"
    remap "__imp_ConnectToPrinterPropertyPage" "__imp_printui$ConnectToPrinterPropertyPage"
    remap "__imp_ConnectToPrinterDlg" "__imp_printui$ConnectToPrinterDlg"
x86:
