x64:
    remap "__imp_RmStartSession" "__imp_rstrtmgr$RmStartSession"
    remap "__imp_RmShutdown" "__imp_rstrtmgr$RmShutdown"
    remap "__imp_RmRestart" "__imp_rstrtmgr$RmRestart"
    remap "__imp_RmReserveHeap" "__imp_rstrtmgr$RmReserveHeap"
    remap "__imp_RmRemoveFilter" "__imp_rstrtmgr$RmRemoveFilter"
    remap "__imp_RmRegisterResources" "__imp_rstrtmgr$RmRegisterResources"
    remap "__imp_RmJoinSession" "__imp_rstrtmgr$RmJoinSession"
    remap "__imp_RmGetList" "__imp_rstrtmgr$RmGetList"
    remap "__imp_RmGetFilterList" "__imp_rstrtmgr$RmGetFilterList"
    remap "__imp_RmEndSession" "__imp_rstrtmgr$RmEndSession"
    remap "__imp_RmCancelCurrentTask" "__imp_rstrtmgr$RmCancelCurrentTask"
    remap "__imp_RmAddFilter" "__imp_rstrtmgr$RmAddFilter"
x86:
    remap "__imp__RmStartSession@12" "__imp__rstrtmgr$RmStartSession@12"
    remap "__imp__RmShutdown@12" "__imp__rstrtmgr$RmShutdown@12"
    remap "__imp__RmRestart@12" "__imp__rstrtmgr$RmRestart@12"
    remap "__imp__RmReserveHeap@4" "__imp__rstrtmgr$RmReserveHeap@4"
    remap "__imp__RmRemoveFilter@16" "__imp__rstrtmgr$RmRemoveFilter@16"
    remap "__imp__RmRegisterResources@28" "__imp__rstrtmgr$RmRegisterResources@28"
    remap "__imp__RmJoinSession@8" "__imp__rstrtmgr$RmJoinSession@8"
    remap "__imp__RmGetList@20" "__imp__rstrtmgr$RmGetList@20"
    remap "__imp__RmGetFilterList@16" "__imp__rstrtmgr$RmGetFilterList@16"
    remap "__imp__RmEndSession@4" "__imp__rstrtmgr$RmEndSession@4"
    remap "__imp__RmCancelCurrentTask@4" "__imp__rstrtmgr$RmCancelCurrentTask@4"
    remap "__imp__RmAddFilter@20" "__imp__rstrtmgr$RmAddFilter@20"
