x64:
    remap "__imp_SsdpStartup" "__imp_ssdpapi$SsdpStartup"
    remap "__imp_SsdpCleanup" "__imp_ssdpapi$SsdpCleanup"
    remap "__imp_RegisterService" "__imp_ssdpapi$RegisterService"
    remap "__imp_RegisterNotification" "__imp_ssdpapi$RegisterNotification"
    remap "__imp_GetNextService" "__imp_ssdpapi$GetNextService"
    remap "__imp_GetFirstService" "__imp_ssdpapi$GetFirstService"
    remap "__imp_FreeSsdpMessage" "__imp_ssdpapi$FreeSsdpMessage"
    remap "__imp_FindServicesClose" "__imp_ssdpapi$FindServicesClose"
    remap "__imp_FindServicesCancel" "__imp_ssdpapi$FindServicesCancel"
    remap "__imp_FindServicesCallback" "__imp_ssdpapi$FindServicesCallback"
    remap "__imp_FindServices" "__imp_ssdpapi$FindServices"
    remap "__imp_DeregisterServiceByUSN" "__imp_ssdpapi$DeregisterServiceByUSN"
    remap "__imp_DeregisterService" "__imp_ssdpapi$DeregisterService"
    remap "__imp_DeregisterNotification" "__imp_ssdpapi$DeregisterNotification"
    remap "__imp_DHSetICSOff" "__imp_ssdpapi$DHSetICSOff"
    remap "__imp_DHSetICSInterfaces" "__imp_ssdpapi$DHSetICSInterfaces"
    remap "__imp_DHEnableDeviceHost" "__imp_ssdpapi$DHEnableDeviceHost"
    remap "__imp_DHDisableDeviceHost" "__imp_ssdpapi$DHDisableDeviceHost"
    remap "__imp_CleanupCache" "__imp_ssdpapi$CleanupCache"
x86:
