x64:
    remap "__imp_TcSetSocketFlow" "__imp_traffic$TcSetSocketFlow"
    remap "__imp_TcSetInterface" "__imp_traffic$TcSetInterface"
    remap "__imp_TcSetFlowW" "__imp_traffic$TcSetFlowW"
    remap "__imp_TcSetFlowA" "__imp_traffic$TcSetFlowA"
    remap "__imp_TcRegisterClient" "__imp_traffic$TcRegisterClient"
    remap "__imp_TcQueryInterface" "__imp_traffic$TcQueryInterface"
    remap "__imp_TcQueryFlowW" "__imp_traffic$TcQueryFlowW"
    remap "__imp_TcQueryFlowA" "__imp_traffic$TcQueryFlowA"
    remap "__imp_TcOpenInterfaceW" "__imp_traffic$TcOpenInterfaceW"
    remap "__imp_TcOpenInterfaceA" "__imp_traffic$TcOpenInterfaceA"
    remap "__imp_TcModifyFlow" "__imp_traffic$TcModifyFlow"
    remap "__imp_TcGetInterfaceList" "__imp_traffic$TcGetInterfaceList"
    remap "__imp_TcGetFlowNameW" "__imp_traffic$TcGetFlowNameW"
    remap "__imp_TcGetFlowNameA" "__imp_traffic$TcGetFlowNameA"
    remap "__imp_TcEnumerateInterfaces" "__imp_traffic$TcEnumerateInterfaces"
    remap "__imp_TcEnumerateFlows" "__imp_traffic$TcEnumerateFlows"
    remap "__imp_TcDeregisterClient" "__imp_traffic$TcDeregisterClient"
    remap "__imp_TcDeleteFlow" "__imp_traffic$TcDeleteFlow"
    remap "__imp_TcDeleteFilter" "__imp_traffic$TcDeleteFilter"
    remap "__imp_TcCloseInterface" "__imp_traffic$TcCloseInterface"
    remap "__imp_TcAddFlow" "__imp_traffic$TcAddFlow"
    remap "__imp_TcAddFilter" "__imp_traffic$TcAddFilter"
x86:
