x64:
    remap "__imp_TxfSetThreadMiniVersionForCreate" "__imp_txfw32$TxfSetThreadMiniVersionForCreate"
    remap "__imp_TxfReadMetadataInfo" "__imp_txfw32$TxfReadMetadataInfo"
    remap "__imp_TxfLogRecordGetGenericType" "__imp_txfw32$TxfLogRecordGetGenericType"
    remap "__imp_TxfLogRecordGetFileName" "__imp_txfw32$TxfLogRecordGetFileName"
    remap "__imp_TxfLogReadRecords" "__imp_txfw32$TxfLogReadRecords"
    remap "__imp_TxfLogDestroyReadContext" "__imp_txfw32$TxfLogDestroyReadContext"
    remap "__imp_TxfLogCreateRangeReadContext" "__imp_txfw32$TxfLogCreateRangeReadContext"
    remap "__imp_TxfLogCreateFileReadContext" "__imp_txfw32$TxfLogCreateFileReadContext"
    remap "__imp_TxfGetThreadMiniVersionForCreate" "__imp_txfw32$TxfGetThreadMiniVersionForCreate"
x86:
    remap "__imp__TxfSetThreadMiniVersionForCreate@4" "__imp__txfw32$TxfSetThreadMiniVersionForCreate@4"
    remap "__imp__TxfReadMetadataInfo@20" "__imp__txfw32$TxfReadMetadataInfo@20"
    remap "__imp__TxfLogRecordGetGenericType@16" "__imp__txfw32$TxfLogRecordGetGenericType@16"
    remap "__imp__TxfLogRecordGetFileName@20" "__imp__txfw32$TxfLogRecordGetFileName@20"
    remap "__imp__TxfLogReadRecords@20" "__imp__txfw32$TxfLogReadRecords@20"
    remap "__imp__TxfLogDestroyReadContext@4" "__imp__txfw32$TxfLogDestroyReadContext@4"
    remap "__imp__TxfLogCreateRangeReadContext@36" "__imp__txfw32$TxfLogCreateRangeReadContext@36"
    remap "__imp__TxfLogCreateFileReadContext@28" "__imp__txfw32$TxfLogCreateFileReadContext@28"
    remap "__imp__TxfGetThreadMiniVersionForCreate@4" "__imp__txfw32$TxfGetThreadMiniVersionForCreate@4"
