x64:
    remap "__imp_WinntIsWorkstation" "__imp_uniplat$WinntIsWorkstation"
    remap "__imp_UnimodemWriteFileEx" "__imp_uniplat$UnimodemWriteFileEx"
    remap "__imp_UnimodemWaitCommEventEx" "__imp_uniplat$UnimodemWaitCommEventEx"
    remap "__imp_UnimodemReadFileEx" "__imp_uniplat$UnimodemReadFileEx"
    remap "__imp_UnimodemQueueUserAPC" "__imp_uniplat$UnimodemQueueUserAPC"
    remap "__imp_UnimodemNotifyTSP" "__imp_uniplat$UnimodemNotifyTSP"
    remap "__imp_UnimodemDeviceIoControlEx" "__imp_uniplat$UnimodemDeviceIoControlEx"
    remap "__imp_UmPlatformInitialize" "__imp_uniplat$UmPlatformInitialize"
    remap "__imp_UmPlatformDeinitialize" "__imp_uniplat$UmPlatformDeinitialize"
    remap "__imp_SyncDeviceIoControl" "__imp_uniplat$SyncDeviceIoControl"
    remap "__imp_StopMonitoringHandle" "__imp_uniplat$StopMonitoringHandle"
    remap "__imp_StopMonitorThread" "__imp_uniplat$StopMonitorThread"
    remap "__imp_StartMonitorThread" "__imp_uniplat$StartMonitorThread"
    remap "__imp_SetUnimodemTimer" "__imp_uniplat$SetUnimodemTimer"
    remap "__imp_ResetCallCount" "__imp_uniplat$ResetCallCount"
    remap "__imp_ReinitOverStruct" "__imp_uniplat$ReinitOverStruct"
    remap "__imp_MonitorHandle" "__imp_uniplat$MonitorHandle"
    remap "__imp_FreeUnimodemTimer" "__imp_uniplat$FreeUnimodemTimer"
    remap "__imp_FreeOverStruct" "__imp_uniplat$FreeOverStruct"
    remap "__imp_DestroyOverStructPool" "__imp_uniplat$DestroyOverStructPool"
    remap "__imp_CreateUnimodemTimer" "__imp_uniplat$CreateUnimodemTimer"
    remap "__imp_CreateOverStructPool" "__imp_uniplat$CreateOverStructPool"
    remap "__imp_CancelUnimodemTimer" "__imp_uniplat$CancelUnimodemTimer"
    remap "__imp_CallEnding" "__imp_uniplat$CallEnding"
    remap "__imp_CallBeginning" "__imp_uniplat$CallBeginning"
    remap "__imp_AllocateOverStructEx" "__imp_uniplat$AllocateOverStructEx"
x86:
