x64:
    remap "__imp_UmWaveAction" "__imp_unimdmat$UmWaveAction"
    remap "__imp_UmSetSpeakerPhoneState" "__imp_unimdmat$UmSetSpeakerPhoneState"
    remap "__imp_UmSetPassthroughMode" "__imp_unimdmat$UmSetPassthroughMode"
    remap "__imp_UmOpenModem" "__imp_unimdmat$UmOpenModem"
    remap "__imp_UmMonitorModem" "__imp_unimdmat$UmMonitorModem"
    remap "__imp_UmLogStringA" "__imp_unimdmat$UmLogStringA"
    remap "__imp_UmLogDiagnostics" "__imp_unimdmat$UmLogDiagnostics"
    remap "__imp_UmIssueCommand" "__imp_unimdmat$UmIssueCommand"
    remap "__imp_UmInitializeModemDriver" "__imp_unimdmat$UmInitializeModemDriver"
    remap "__imp_UmInitModem" "__imp_unimdmat$UmInitModem"
    remap "__imp_UmHangupModem" "__imp_unimdmat$UmHangupModem"
    remap "__imp_UmGetDiagnostics" "__imp_unimdmat$UmGetDiagnostics"
    remap "__imp_UmGenerateDigit" "__imp_unimdmat$UmGenerateDigit"
    remap "__imp_UmDuplicateDeviceHandle" "__imp_unimdmat$UmDuplicateDeviceHandle"
    remap "__imp_UmDialModem" "__imp_unimdmat$UmDialModem"
    remap "__imp_UmDeinitializeModemDriver" "__imp_unimdmat$UmDeinitializeModemDriver"
    remap "__imp_UmCloseModem" "__imp_unimdmat$UmCloseModem"
    remap "__imp_UmAnswerModem" "__imp_unimdmat$UmAnswerModem"
    remap "__imp_UmAbortCurrentModemCommand" "__imp_unimdmat$UmAbortCurrentModemCommand"
x86:
