x64:
    remap "__imp_pfnWow64PerfMonitorCall" "__imp_wow64$pfnWow64PerfMonitorCall"
    remap "__imp_Wow64SystemServiceEx" "__imp_wow64$Wow64SystemServiceEx"
    remap "__imp_Wow64SystemService" "__imp_wow64$Wow64SystemService"
    remap "__imp_Wow64StartupContextToContextX86" "__imp_wow64$Wow64StartupContextToContextX86"
    remap "__imp_Wow64ShallowThunkSIZE_T64TO32" "__imp_wow64$Wow64ShallowThunkSIZE_T64TO32"
    remap "__imp_Wow64ShallowThunkSIZE_T32TO64" "__imp_wow64$Wow64ShallowThunkSIZE_T32TO64"
    remap "__imp_Wow64ShallowThunkAllocSecurityQualityOfService32TO64_FNC" "__imp_wow64$Wow64ShallowThunkAllocSecurityQualityOfService32TO64_FNC"
    remap "__imp_Wow64ShallowThunkAllocObjectAttributes32TO64_FNC" "__imp_wow64$Wow64ShallowThunkAllocObjectAttributes32TO64_FNC"
    remap "__imp_Wow64RaiseException" "__imp_wow64$Wow64RaiseException"
    remap "__imp_Wow64PrepareForException" "__imp_wow64$Wow64PrepareForException"
    remap "__imp_Wow64PrepareForDebuggerAttach" "__imp_wow64$Wow64PrepareForDebuggerAttach"
    remap "__imp_Wow64OpenConfigKey" "__imp_wow64$Wow64OpenConfigKey"
    remap "__imp_Wow64LogPrint" "__imp_wow64$Wow64LogPrint"
    remap "__imp_Wow64LdrpInitialize" "__imp_wow64$Wow64LdrpInitialize"
    remap "__imp_Wow64KiUserCallbackDispatcher" "__imp_wow64$Wow64KiUserCallbackDispatcher"
    remap "__imp_Wow64GetWow64ImageOption" "__imp_wow64$Wow64GetWow64ImageOption"
    remap "__imp_Wow64FreeHeap" "__imp_wow64$Wow64FreeHeap"
    remap "__imp_Wow64ExecuteFlags" "__imp_wow64$Wow64ExecuteFlags"
    remap "__imp_Wow64EmulateAtlThunk" "__imp_wow64$Wow64EmulateAtlThunk"
    remap "__imp_Wow64CheckIfNXEnabled" "__imp_wow64$Wow64CheckIfNXEnabled"
    remap "__imp_Wow64Assert" "__imp_wow64$Wow64Assert"
    remap "__imp_Wow64ApcRoutine" "__imp_wow64$Wow64ApcRoutine"
    remap "__imp_Wow64AllocateTemp" "__imp_wow64$Wow64AllocateTemp"
    remap "__imp_Wow64AllocateHeap" "__imp_wow64$Wow64AllocateHeap"
x86:
