# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_AvSetMmThreadPriority" "__imp_avrt$AvSetMmThreadPriority"
    remap "__imp_AvSetMmThreadCharacteristicsW" "__imp_avrt$AvSetMmThreadCharacteristicsW"
    remap "__imp_AvSetMmThreadCharacteristicsA" "__imp_avrt$AvSetMmThreadCharacteristicsA"
    remap "__imp_AvSetMmMaxThreadCharacteristicsW" "__imp_avrt$AvSetMmMaxThreadCharacteristicsW"
    remap "__imp_AvSetMmMaxThreadCharacteristicsA" "__imp_avrt$AvSetMmMaxThreadCharacteristicsA"
    remap "__imp_AvRtWaitOnThreadOrderingGroup" "__imp_avrt$AvRtWaitOnThreadOrderingGroup"
    remap "__imp_AvRtLeaveThreadOrderingGroup" "__imp_avrt$AvRtLeaveThreadOrderingGroup"
    remap "__imp_AvRtJoinThreadOrderingGroup" "__imp_avrt$AvRtJoinThreadOrderingGroup"
    remap "__imp_AvRtDeleteThreadOrderingGroup" "__imp_avrt$AvRtDeleteThreadOrderingGroup"
    remap "__imp_AvRtCreateThreadOrderingGroupExW" "__imp_avrt$AvRtCreateThreadOrderingGroupExW"
    remap "__imp_AvRtCreateThreadOrderingGroupExA" "__imp_avrt$AvRtCreateThreadOrderingGroupExA"
    remap "__imp_AvRtCreateThreadOrderingGroup" "__imp_avrt$AvRtCreateThreadOrderingGroup"
    remap "__imp_AvRevertMmThreadCharacteristics" "__imp_avrt$AvRevertMmThreadCharacteristics"
    remap "__imp_AvQuerySystemResponsiveness" "__imp_avrt$AvQuerySystemResponsiveness"
x86:
    remap "__imp__AvSetMmThreadPriority@8" "__imp__avrt$AvSetMmThreadPriority@8"
    remap "__imp__AvSetMmThreadCharacteristicsW@8" "__imp__avrt$AvSetMmThreadCharacteristicsW@8"
    remap "__imp__AvSetMmThreadCharacteristicsA@8" "__imp__avrt$AvSetMmThreadCharacteristicsA@8"
    remap "__imp__AvSetMmMaxThreadCharacteristicsW@12" "__imp__avrt$AvSetMmMaxThreadCharacteristicsW@12"
    remap "__imp__AvSetMmMaxThreadCharacteristicsA@12" "__imp__avrt$AvSetMmMaxThreadCharacteristicsA@12"
    remap "__imp__AvRtWaitOnThreadOrderingGroup@4" "__imp__avrt$AvRtWaitOnThreadOrderingGroup@4"
    remap "__imp__AvRtLeaveThreadOrderingGroup@4" "__imp__avrt$AvRtLeaveThreadOrderingGroup@4"
    remap "__imp__AvRtJoinThreadOrderingGroup@12" "__imp__avrt$AvRtJoinThreadOrderingGroup@12"
    remap "__imp__AvRtDeleteThreadOrderingGroup@4" "__imp__avrt$AvRtDeleteThreadOrderingGroup@4"
    remap "__imp__AvRtCreateThreadOrderingGroupExW@20" "__imp__avrt$AvRtCreateThreadOrderingGroupExW@20"
    remap "__imp__AvRtCreateThreadOrderingGroupExA@20" "__imp__avrt$AvRtCreateThreadOrderingGroupExA@20"
    remap "__imp__AvRtCreateThreadOrderingGroup@16" "__imp__avrt$AvRtCreateThreadOrderingGroup@16"
    remap "__imp__AvRevertMmThreadCharacteristics@4" "__imp__avrt$AvRevertMmThreadCharacteristics@4"
    remap "__imp__AvQuerySystemResponsiveness@8" "__imp__avrt$AvQuerySystemResponsiveness@8"
