x64:
    remap "__imp_ServiceMain" "__imp_appmgmts$ServiceMain"
    remap "__imp_ReleasePackageInfo" "__imp_appmgmts$ReleasePackageInfo"
    remap "__imp_ReleasePackageDetail" "__imp_appmgmts$ReleasePackageDetail"
    remap "__imp_ReleaseAppCategoryInfoList" "__imp_appmgmts$ReleaseAppCategoryInfoList"
    remap "__imp_ProcessGroupPolicyObjectsEx" "__imp_appmgmts$ProcessGroupPolicyObjectsEx"
    remap "__imp_IID_IClassAdmin" "__imp_appmgmts$IID_IClassAdmin"
    remap "__imp_GenerateGroupPolicy" "__imp_appmgmts$GenerateGroupPolicy"
    remap "__imp_CsUnregisterAppCategory" "__imp_appmgmts$CsUnregisterAppCategory"
    remap "__imp_CsSetOptions" "__imp_appmgmts$CsSetOptions"
    remap "__imp_CsServerGetClassStore" "__imp_appmgmts$CsServerGetClassStore"
    remap "__imp_CsRegisterAppCategory" "__imp_appmgmts$CsRegisterAppCategory"
    remap "__imp_CsGetClassStorePath" "__imp_appmgmts$CsGetClassStorePath"
    remap "__imp_CsGetClassStore" "__imp_appmgmts$CsGetClassStore"
    remap "__imp_CsGetClassAccess" "__imp_appmgmts$CsGetClassAccess"
    remap "__imp_CsGetAppCategories" "__imp_appmgmts$CsGetAppCategories"
    remap "__imp_CsEnumApps" "__imp_appmgmts$CsEnumApps"
    remap "__imp_CsCreateClassStore" "__imp_appmgmts$CsCreateClassStore"
x86:
