x64:
    remap "__imp_VidSolidColorFill" "__imp_bootvid$VidSolidColorFill"
    remap "__imp_VidSetTextColor" "__imp_bootvid$VidSetTextColor"
    remap "__imp_VidSetScrollRegion" "__imp_bootvid$VidSetScrollRegion"
    remap "__imp_VidScreenToBufferBlt" "__imp_bootvid$VidScreenToBufferBlt"
    remap "__imp_VidResetDisplay" "__imp_bootvid$VidResetDisplay"
    remap "__imp_VidInitialize" "__imp_bootvid$VidInitialize"
    remap "__imp_VidDisplayStringXY" "__imp_bootvid$VidDisplayStringXY"
    remap "__imp_VidDisplayString" "__imp_bootvid$VidDisplayString"
    remap "__imp_VidCleanUp" "__imp_bootvid$VidCleanUp"
    remap "__imp_VidBufferToScreenBlt" "__imp_bootvid$VidBufferToScreenBlt"
    remap "__imp_VidBitBltEx" "__imp_bootvid$VidBitBltEx"
    remap "__imp_VidBitBlt" "__imp_bootvid$VidBitBlt"
x86:
    remap "__imp__VidSolidColorFill@20" "__imp__bootvid$VidSolidColorFill@20"
    remap "__imp__VidSetTextColor@4" "__imp__bootvid$VidSetTextColor@4"
    remap "__imp__VidSetScrollRegion@16" "__imp__bootvid$VidSetScrollRegion@16"
    remap "__imp__VidScreenToBufferBlt@24" "__imp__bootvid$VidScreenToBufferBlt@24"
    remap "__imp__VidResetDisplay@4" "__imp__bootvid$VidResetDisplay@4"
    remap "__imp__VidInitialize@8" "__imp__bootvid$VidInitialize@8"
    remap "__imp__VidDisplayStringXY@16" "__imp__bootvid$VidDisplayStringXY@16"
    remap "__imp__VidDisplayString@4" "__imp__bootvid$VidDisplayString@4"
    remap "__imp__VidCleanUp@0" "__imp__bootvid$VidCleanUp@0"
    remap "__imp__VidBufferToScreenBlt@24" "__imp__bootvid$VidBufferToScreenBlt@24"
    remap "__imp__VidBitBlt@12" "__imp__bootvid$VidBitBlt@12"
