# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_I_InvokeCommand" "__imp_cryptext$I_InvokeCommand"
    remap "__imp_CryptExtOpenSTRW" "__imp_cryptext$CryptExtOpenSTRW"
    remap "__imp_CryptExtOpenSTR" "__imp_cryptext$CryptExtOpenSTR"
    remap "__imp_CryptExtOpenPKCS7W" "__imp_cryptext$CryptExtOpenPKCS7W"
    remap "__imp_CryptExtOpenPKCS7" "__imp_cryptext$CryptExtOpenPKCS7"
    remap "__imp_CryptExtOpenP7RW" "__imp_cryptext$CryptExtOpenP7RW"
    remap "__imp_CryptExtOpenP7R" "__imp_cryptext$CryptExtOpenP7R"
    remap "__imp_CryptExtOpenP10W" "__imp_cryptext$CryptExtOpenP10W"
    remap "__imp_CryptExtOpenP10" "__imp_cryptext$CryptExtOpenP10"
    remap "__imp_CryptExtOpenCTLW" "__imp_cryptext$CryptExtOpenCTLW"
    remap "__imp_CryptExtOpenCTL" "__imp_cryptext$CryptExtOpenCTL"
    remap "__imp_CryptExtOpenCRLW" "__imp_cryptext$CryptExtOpenCRLW"
    remap "__imp_CryptExtOpenCRL" "__imp_cryptext$CryptExtOpenCRL"
    remap "__imp_CryptExtOpenCERW" "__imp_cryptext$CryptExtOpenCERW"
    remap "__imp_CryptExtOpenCER" "__imp_cryptext$CryptExtOpenCER"
    remap "__imp_CryptExtOpenCATW" "__imp_cryptext$CryptExtOpenCATW"
    remap "__imp_CryptExtOpenCAT" "__imp_cryptext$CryptExtOpenCAT"
    remap "__imp_CryptExtAddSPCW" "__imp_cryptext$CryptExtAddSPCW"
    remap "__imp_CryptExtAddSPC" "__imp_cryptext$CryptExtAddSPC"
    remap "__imp_CryptExtAddPFXW" "__imp_cryptext$CryptExtAddPFXW"
    remap "__imp_CryptExtAddPFXMachineOnlyAndHwndW" "__imp_cryptext$CryptExtAddPFXMachineOnlyAndHwndW"
    remap "__imp_CryptExtAddPFX" "__imp_cryptext$CryptExtAddPFX"
    remap "__imp_CryptExtAddP7RW" "__imp_cryptext$CryptExtAddP7RW"
    remap "__imp_CryptExtAddP7R" "__imp_cryptext$CryptExtAddP7R"
    remap "__imp_CryptExtAddCTLW" "__imp_cryptext$CryptExtAddCTLW"
    remap "__imp_CryptExtAddCTL" "__imp_cryptext$CryptExtAddCTL"
    remap "__imp_CryptExtAddCRLW" "__imp_cryptext$CryptExtAddCRLW"
    remap "__imp_CryptExtAddCRL" "__imp_cryptext$CryptExtAddCRL"
    remap "__imp_CryptExtAddCERW" "__imp_cryptext$CryptExtAddCERW"
    remap "__imp_CryptExtAddCERMachineOnlyAndHwndW" "__imp_cryptext$CryptExtAddCERMachineOnlyAndHwndW"
    remap "__imp_CryptExtAddCER" "__imp_cryptext$CryptExtAddCER"
x86:
