# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_GetFriendlyNameOfCertW" "__imp_cryptdlg$GetFriendlyNameOfCertW"
    remap "__imp_GetFriendlyNameOfCertA" "__imp_cryptdlg$GetFriendlyNameOfCertA"
    remap "__imp_FormatVerisignExtension" "__imp_cryptdlg$FormatVerisignExtension"
    remap "__imp_FormatPKIXEmailProtection" "__imp_cryptdlg$FormatPKIXEmailProtection"
    remap "__imp_EncodeRecipientID" "__imp_cryptdlg$EncodeRecipientID"
    remap "__imp_EncodeAttrSequence" "__imp_cryptdlg$EncodeAttrSequence"
    remap "__imp_DllUnregisterServer" "__imp_cryptdlg$DllUnregisterServer"
    remap "__imp_DllRegisterServer" "__imp_cryptdlg$DllRegisterServer"
    remap "__imp_DecodeRecipientID" "__imp_cryptdlg$DecodeRecipientID"
    remap "__imp_DecodeAttrSequence" "__imp_cryptdlg$DecodeAttrSequence"
    remap "__imp_CertViewPropertiesW" "__imp_cryptdlg$CertViewPropertiesW"
    remap "__imp_CertViewPropertiesA" "__imp_cryptdlg$CertViewPropertiesA"
    remap "__imp_CertTrustInit" "__imp_cryptdlg$CertTrustInit"
    remap "__imp_CertTrustFinalPolicy" "__imp_cryptdlg$CertTrustFinalPolicy"
    remap "__imp_CertTrustCleanup" "__imp_cryptdlg$CertTrustCleanup"
    remap "__imp_CertTrustCertPolicy" "__imp_cryptdlg$CertTrustCertPolicy"
    remap "__imp_CertSelectCertificateW" "__imp_cryptdlg$CertSelectCertificateW"
    remap "__imp_CertSelectCertificateA" "__imp_cryptdlg$CertSelectCertificateA"
    remap "__imp_CertModifyCertificatesToTrust" "__imp_cryptdlg$CertModifyCertificatesToTrust"
    remap "__imp_CertConfigureTrustW" "__imp_cryptdlg$CertConfigureTrustW"
    remap "__imp_CertConfigureTrustA" "__imp_cryptdlg$CertConfigureTrustA"
x86:
