# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_SystemFunction041" "__imp_cryptbase$SystemFunction041"
    remap "__imp_SystemFunction040" "__imp_cryptbase$SystemFunction040"
    remap "__imp_SystemFunction036" "__imp_cryptbase$SystemFunction036"
    remap "__imp_SystemFunction034" "__imp_cryptbase$SystemFunction034"
    remap "__imp_SystemFunction029" "__imp_cryptbase$SystemFunction029"
    remap "__imp_SystemFunction028" "__imp_cryptbase$SystemFunction028"
    remap "__imp_SystemFunction005" "__imp_cryptbase$SystemFunction005"
    remap "__imp_SystemFunction004" "__imp_cryptbase$SystemFunction004"
    remap "__imp_SystemFunction003" "__imp_cryptbase$SystemFunction003"
    remap "__imp_SystemFunction002" "__imp_cryptbase$SystemFunction002"
    remap "__imp_SystemFunction001" "__imp_cryptbase$SystemFunction001"
x86:
    remap "__imp__SystemFunction041" "__imp__cryptbase$SystemFunction041"
    remap "__imp__SystemFunction040" "__imp__cryptbase$SystemFunction040"
    remap "__imp__SystemFunction036" "__imp__cryptbase$SystemFunction036"
    remap "__imp__SystemFunction034" "__imp__cryptbase$SystemFunction034"
    remap "__imp__SystemFunction029" "__imp__cryptbase$SystemFunction029"
    remap "__imp__SystemFunction028" "__imp__cryptbase$SystemFunction028"
    remap "__imp__SystemFunction005" "__imp__cryptbase$SystemFunction005"
    remap "__imp__SystemFunction004" "__imp__cryptbase$SystemFunction004"
    remap "__imp__SystemFunction003" "__imp__cryptbase$SystemFunction003"
    remap "__imp__SystemFunction002" "__imp__cryptbase$SystemFunction002"
    remap "__imp__SystemFunction001" "__imp__cryptbase$SystemFunction001"
