# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_CsrValidateMessageString" "__imp_csrsrv$CsrValidateMessageString"
    remap "__imp_CsrValidateMessageBuffer" "__imp_csrsrv$CsrValidateMessageBuffer"
    remap "__imp_CsrUnlockThread" "__imp_csrsrv$CsrUnlockThread"
    remap "__imp_CsrUnlockProcess" "__imp_csrsrv$CsrUnlockProcess"
    remap "__imp_CsrUnhandledExceptionFilter" "__imp_csrsrv$CsrUnhandledExceptionFilter"
    remap "__imp_CsrShutdownProcesses" "__imp_csrsrv$CsrShutdownProcesses"
    remap "__imp_CsrSetForegroundPriority" "__imp_csrsrv$CsrSetForegroundPriority"
    remap "__imp_CsrSetCallingSpooler" "__imp_csrsrv$CsrSetCallingSpooler"
    remap "__imp_CsrSetBackgroundPriority" "__imp_csrsrv$CsrSetBackgroundPriority"
    remap "__imp_CsrServerInitialization" "__imp_csrsrv$CsrServerInitialization"
    remap "__imp_CsrRevertToSelf" "__imp_csrsrv$CsrRevertToSelf"
    remap "__imp_CsrReferenceThread" "__imp_csrsrv$CsrReferenceThread"
    remap "__imp_CsrQueryApiPort" "__imp_csrsrv$CsrQueryApiPort"
    remap "__imp_CsrPopulateDosDevices" "__imp_csrsrv$CsrPopulateDosDevices"
    remap "__imp_CsrNotifyWait" "__imp_csrsrv$CsrNotifyWait"
    remap "__imp_CsrMoveSatisfiedWait" "__imp_csrsrv$CsrMoveSatisfiedWait"
    remap "__imp_CsrLockThreadByClientId" "__imp_csrsrv$CsrLockThreadByClientId"
    remap "__imp_CsrLockProcessByClientId" "__imp_csrsrv$CsrLockProcessByClientId"
    remap "__imp_CsrImpersonateClient" "__imp_csrsrv$CsrImpersonateClient"
    remap "__imp_CsrGetProcessLuid" "__imp_csrsrv$CsrGetProcessLuid"
    remap "__imp_CsrExecServerThread" "__imp_csrsrv$CsrExecServerThread"
    remap "__imp_CsrDestroyThread" "__imp_csrsrv$CsrDestroyThread"
    remap "__imp_CsrDestroyProcess" "__imp_csrsrv$CsrDestroyProcess"
    remap "__imp_CsrDereferenceWait" "__imp_csrsrv$CsrDereferenceWait"
    remap "__imp_CsrDereferenceThread" "__imp_csrsrv$CsrDereferenceThread"
    remap "__imp_CsrDereferenceProcess" "__imp_csrsrv$CsrDereferenceProcess"
    remap "__imp_CsrDebugProcessStop" "__imp_csrsrv$CsrDebugProcessStop"
    remap "__imp_CsrDebugProcess" "__imp_csrsrv$CsrDebugProcess"
    remap "__imp_CsrCreateWait" "__imp_csrsrv$CsrCreateWait"
    remap "__imp_CsrCreateThread" "__imp_csrsrv$CsrCreateThread"
    remap "__imp_CsrCreateRemoteThread" "__imp_csrsrv$CsrCreateRemoteThread"
    remap "__imp_CsrCreateProcess" "__imp_csrsrv$CsrCreateProcess"
    remap "__imp_CsrConnectToUser" "__imp_csrsrv$CsrConnectToUser"
    remap "__imp_CsrCallServerFromServer" "__imp_csrsrv$CsrCallServerFromServer"
    remap "__imp_CsrAddStaticServerThread" "__imp_csrsrv$CsrAddStaticServerThread"
x86:
