x64:
    remap "__imp_UnregisterPagesLink" "__imp_connect$UnregisterPagesLink"
    remap "__imp_UnregisterPage" "__imp_connect$UnregisterPage"
    remap "__imp_RegisterPageWithPage" "__imp_connect$RegisterPageWithPage"
    remap "__imp_IsUniqueConnectionName" "__imp_connect$IsUniqueConnectionName"
    remap "__imp_IsInternetConnectedGUID" "__imp_connect$IsInternetConnectedGUID"
    remap "__imp_IsInternetConnected" "__imp_connect$IsInternetConnected"
    remap "__imp_HrIsInternetConnectedGUID" "__imp_connect$HrIsInternetConnectedGUID"
    remap "__imp_HrIsInternetConnected" "__imp_connect$HrIsInternetConnected"
    remap "__imp_GetVPNConnected" "__imp_connect$GetVPNConnected"
    remap "__imp_GetNetworkConnected" "__imp_connect$GetNetworkConnected"
    remap "__imp_GetInternetConnected" "__imp_connect$GetInternetConnected"
    remap "__imp_CreateVPNConnection" "__imp_connect$CreateVPNConnection"
    remap "__imp_AddConnectionOptionListEntries" "__imp_connect$AddConnectionOptionListEntries"
x86:
    remap "__imp__UnregisterPagesLink@8" "__imp__connect$UnregisterPagesLink@8"
    remap "__imp__UnregisterPage@8" "__imp__connect$UnregisterPage@8"
    remap "__imp__RegisterPageWithPage@28" "__imp__connect$RegisterPageWithPage@28"
    remap "__imp__IsUniqueConnectionName@4" "__imp__connect$IsUniqueConnectionName@4"
    remap "__imp__IsInternetConnectedGUID@8" "__imp__connect$IsInternetConnectedGUID@8"
    remap "__imp__IsInternetConnected@0" "__imp__connect$IsInternetConnected@0"
    remap "__imp__GetVPNConnected@24" "__imp__connect$GetVPNConnected@24"
    remap "__imp__GetNetworkConnected@24" "__imp__connect$GetNetworkConnected@24"
    remap "__imp__GetInternetConnected@24" "__imp__connect$GetInternetConnected@24"
    remap "__imp__DllGetClassObject@12" "__imp__connect$DllGetClassObject@12"
    remap "__imp__DllCanUnloadNow@0" "__imp__connect$DllCanUnloadNow@0"
    remap "__imp__CreateVPNConnection@24" "__imp__connect$CreateVPNConnection@24"
    remap "__imp__AddConnectionOptionListEntries@12" "__imp__connect$AddConnectionOptionListEntries@12"
