# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_PhoneBookUnload" "__imp_cmpbk32$PhoneBookUnload"
    remap "__imp_PhoneBookParseInfoA" "__imp_cmpbk32$PhoneBookParseInfoA"
    remap "__imp_PhoneBookMergeChanges" "__imp_cmpbk32$PhoneBookMergeChanges"
    remap "__imp_PhoneBookMatchFilter" "__imp_cmpbk32$PhoneBookMatchFilter"
    remap "__imp_PhoneBookLoad" "__imp_cmpbk32$PhoneBookLoad"
    remap "__imp_PhoneBookHasPhoneType" "__imp_cmpbk32$PhoneBookHasPhoneType"
    remap "__imp_PhoneBookGetRegionNameA" "__imp_cmpbk32$PhoneBookGetRegionNameA"
    remap "__imp_PhoneBookGetPhoneType" "__imp_cmpbk32$PhoneBookGetPhoneType"
    remap "__imp_PhoneBookGetPhoneNonCanonicalA" "__imp_cmpbk32$PhoneBookGetPhoneNonCanonicalA"
    remap "__imp_PhoneBookGetPhoneDispA" "__imp_cmpbk32$PhoneBookGetPhoneDispA"
    remap "__imp_PhoneBookGetPhoneDescA" "__imp_cmpbk32$PhoneBookGetPhoneDescA"
    remap "__imp_PhoneBookGetPhoneDUNA" "__imp_cmpbk32$PhoneBookGetPhoneDUNA"
    remap "__imp_PhoneBookGetPhoneCanonicalA" "__imp_cmpbk32$PhoneBookGetPhoneCanonicalA"
    remap "__imp_PhoneBookGetCurrentCountryId" "__imp_cmpbk32$PhoneBookGetCurrentCountryId"
    remap "__imp_PhoneBookGetCountryNameW" "__imp_cmpbk32$PhoneBookGetCountryNameW"
    remap "__imp_PhoneBookGetCountryNameA" "__imp_cmpbk32$PhoneBookGetCountryNameA"
    remap "__imp_PhoneBookGetCountryId" "__imp_cmpbk32$PhoneBookGetCountryId"
    remap "__imp_PhoneBookFreeFilter" "__imp_cmpbk32$PhoneBookFreeFilter"
    remap "__imp_PhoneBookEnumRegions" "__imp_cmpbk32$PhoneBookEnumRegions"
    remap "__imp_PhoneBookEnumNumbersWithRegionsZero" "__imp_cmpbk32$PhoneBookEnumNumbersWithRegionsZero"
    remap "__imp_PhoneBookEnumNumbers" "__imp_cmpbk32$PhoneBookEnumNumbers"
    remap "__imp_PhoneBookEnumCountries" "__imp_cmpbk32$PhoneBookEnumCountries"
    remap "__imp_PhoneBookCopyFilter" "__imp_cmpbk32$PhoneBookCopyFilter"
x86:
