x64:
    remap "__imp_CreateServerRequestsZ" "__imp_dmvdsitf$CreateServerRequestsZ"
    remap "__imp_CreateDataCacheZ" "__imp_dmvdsitf$CreateDataCacheZ"
    remap "__imp_?GetWaitCursor@CDMSnapin@@QEAAHXZ" "__imp_dmvdsitf$?GetWaitCursor@CDMSnapin@@QEAAHXZ"
    remap "__imp_?GetVolumeCount@CDataCache@@QEAAKXZ" "__imp_dmvdsitf$?GetVolumeCount@CDataCache@@QEAAKXZ"
    remap "__imp_?GetTopViewStyle@CDMSnapin@@QEAAHXZ" "__imp_dmvdsitf$?GetTopViewStyle@CDMSnapin@@QEAAHXZ"
    remap "__imp_?GetServerName@CDataCache@@QEAA?AVCString@@XZ" "__imp_dmvdsitf$?GetServerName@CDataCache@@QEAA?AVCString@@XZ"
    remap "__imp_?GetRegionScaling@CDMSnapin@@QEAAHXZ" "__imp_dmvdsitf$?GetRegionScaling@CDMSnapin@@QEAAHXZ"
    remap "__imp_?GetRegionColorStructPtr@CTaskData@@QEAAXPEAPEAU_REGION_COLORS@@AEAH@Z" "__imp_dmvdsitf$?GetRegionColorStructPtr@CTaskData@@QEAAXPEAPEAU_REGION_COLORS@@AEAH@Z"
    remap "__imp_?GetOcxFrameCWndPtr@CTaskData@@QEAAPEAVCWnd@@XZ" "__imp_dmvdsitf$?GetOcxFrameCWndPtr@CTaskData@@QEAAPEAVCWnd@@XZ"
    remap "__imp_?GetNumMembers@CDMNodeObj@@QEAAKXZ" "__imp_dmvdsitf$?GetNumMembers@CDMNodeObj@@QEAAKXZ"
    remap "__imp_?GetListBehavior@CDMSnapin@@QEAAHXZ" "__imp_dmvdsitf$?GetListBehavior@CDMSnapin@@QEAAHXZ"
    remap "__imp_?GetLdmObjectId@CDMNodeObj@@QEAA_JXZ" "__imp_dmvdsitf$?GetLdmObjectId@CDMNodeObj@@QEAA_JXZ"
    remap "__imp_?GetFilterToggle@CDMSnapin@@QEAAHXZ" "__imp_dmvdsitf$?GetFilterToggle@CDMSnapin@@QEAAHXZ"
    remap "__imp_?GetDiskScaling@CDMSnapin@@QEAAHXZ" "__imp_dmvdsitf$?GetDiskScaling@CDMSnapin@@QEAAHXZ"
    remap "__imp_?GetDiskCount@CDataCache@@QEAAKXZ" "__imp_dmvdsitf$?GetDiskCount@CDataCache@@QEAAKXZ"
    remap "__imp_?GetBottomViewStyle@CDMSnapin@@QEAAHXZ" "__imp_dmvdsitf$?GetBottomViewStyle@CDMSnapin@@QEAAHXZ"
    remap "__imp_?AddLDMObjMapEntry@CDataCache@@QEAAXPEAU_LDM_OBJ_MAP_ENTRY@@@Z" "__imp_dmvdsitf$?AddLDMObjMapEntry@CDataCache@@QEAAXPEAU_LDM_OBJ_MAP_ENTRY@@@Z"
x86:
