x64:
    remap "__imp_WinWatchOpen" "__imp_dciman32$WinWatchOpen"
    remap "__imp_WinWatchNotify" "__imp_dciman32$WinWatchNotify"
    remap "__imp_WinWatchGetClipList" "__imp_dciman32$WinWatchGetClipList"
    remap "__imp_WinWatchDidStatusChange" "__imp_dciman32$WinWatchDidStatusChange"
    remap "__imp_WinWatchClose" "__imp_dciman32$WinWatchClose"
    remap "__imp_GetWindowRegionData" "__imp_dciman32$GetWindowRegionData"
    remap "__imp_GetDCRegionData" "__imp_dciman32$GetDCRegionData"
    remap "__imp_DCISetSrcDestClip" "__imp_dciman32$DCISetSrcDestClip"
    remap "__imp_DCISetDestination" "__imp_dciman32$DCISetDestination"
    remap "__imp_DCISetClipList" "__imp_dciman32$DCISetClipList"
    remap "__imp_DCIOpenProvider" "__imp_dciman32$DCIOpenProvider"
    remap "__imp_DCIEnum" "__imp_dciman32$DCIEnum"
    remap "__imp_DCIEndAccess" "__imp_dciman32$DCIEndAccess"
    remap "__imp_DCIDraw" "__imp_dciman32$DCIDraw"
    remap "__imp_DCIDestroy" "__imp_dciman32$DCIDestroy"
    remap "__imp_DCICreatePrimary" "__imp_dciman32$DCICreatePrimary"
    remap "__imp_DCICreateOverlay" "__imp_dciman32$DCICreateOverlay"
    remap "__imp_DCICreateOffscreen" "__imp_dciman32$DCICreateOffscreen"
    remap "__imp_DCICloseProvider" "__imp_dciman32$DCICloseProvider"
    remap "__imp_DCIBeginAccess" "__imp_dciman32$DCIBeginAccess"
x86:
