# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_TranslateError" "__imp_dmutil$TranslateError"
    remap "__imp_SzwFromSza" "__imp_dmutil$SzwFromSza"
    remap "__imp_SzwDupSzw" "__imp_dmutil$SzwDupSzw"
    remap "__imp_ShowMessageValist" "__imp_dmutil$ShowMessageValist"
    remap "__imp_ShowMessage" "__imp_dmutil$ShowMessage"
    remap "__imp_SafeLoadVdsService" "__imp_dmutil$SafeLoadVdsService"
    remap "__imp_RgszwFromValist" "__imp_dmutil$RgszwFromValist"
    remap "__imp_RgszwFromArgs" "__imp_dmutil$RgszwFromArgs"
    remap "__imp_RgszwDupRgszw" "__imp_dmutil$RgszwDupRgszw"
    remap "__imp_LowNtWriteFile" "__imp_dmutil$LowNtWriteFile"
    remap "__imp_LowNtReadOnlyAttributeOff" "__imp_dmutil$LowNtReadOnlyAttributeOff"
    remap "__imp_LowNtReadFile" "__imp_dmutil$LowNtReadFile"
    remap "__imp_LowNtAddBootEntry" "__imp_dmutil$LowNtAddBootEntry"
    remap "__imp_LowGetPartitionInfo" "__imp_dmutil$LowGetPartitionInfo"
    remap "__imp_LowAcquirePrivilege" "__imp_dmutil$LowAcquirePrivilege"
    remap "__imp_IsPersonalSKU" "__imp_dmutil$IsPersonalSKU"
    remap "__imp_GetSystemVolume" "__imp_dmutil$GetSystemVolume"
    remap "__imp_GetInstallDirectoryPath" "__imp_dmutil$GetInstallDirectoryPath"
    remap "__imp_GetErrorData" "__imp_dmutil$GetErrorData"
    remap "__imp_FreeRgszw" "__imp_dmutil$FreeRgszw"
    remap "__imp_FTraceValist" "__imp_dmutil$FTraceValist"
    remap "__imp_FTrace" "__imp_dmutil$FTrace"
    remap "__imp_DynamicSupport" "__imp_dmutil$DynamicSupport"
    remap "__imp_DmCommonNtOpenFile" "__imp_dmutil$DmCommonNtOpenFile"
    remap "__imp_DisplayErrorRgszw" "__imp_dmutil$DisplayErrorRgszw"
    remap "__imp_DisplayError" "__imp_dmutil$DisplayError"
    remap "__imp_CoDisableDynamicVolumes" "__imp_dmutil$CoDisableDynamicVolumes"
    remap "__imp_AddEntryBootFileMbr" "__imp_dmutil$AddEntryBootFileMbr"
    remap "__imp_AddEntryBootFileGpt" "__imp_dmutil$AddEntryBootFileGpt"
x86:
