# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_StoreSetSearchSubTree" "__imp_dsauth$StoreSetSearchSubTree"
    remap "__imp_StoreSetSearchOneLevel" "__imp_dsauth$StoreSetSearchOneLevel"
    remap "__imp_StoreSearchGetNext" "__imp_dsauth$StoreSearchGetNext"
    remap "__imp_StoreInitHandle" "__imp_dsauth$StoreInitHandle"
    remap "__imp_StoreGetHandle" "__imp_dsauth$StoreGetHandle"
    remap "__imp_StoreEndSearch" "__imp_dsauth$StoreEndSearch"
    remap "__imp_StoreDeleteObject" "__imp_dsauth$StoreDeleteObject"
    remap "__imp_StoreCreateObjectVA" "__imp_dsauth$StoreCreateObjectVA"
    remap "__imp_StoreCollectAttributes" "__imp_dsauth$StoreCollectAttributes"
    remap "__imp_StoreCleanupHandle" "__imp_dsauth$StoreCleanupHandle"
    remap "__imp_StoreBeginSearch" "__imp_dsauth$StoreBeginSearch"
    remap "__imp_DhcpEnumServersDS" "__imp_dsauth$DhcpEnumServersDS"
    remap "__imp_DhcpDsValidateService" "__imp_dsauth$DhcpDsValidateService"
    remap "__imp_DhcpDsSetLists" "__imp_dsauth$DhcpDsSetLists"
    remap "__imp_DhcpDsInitDS" "__imp_dsauth$DhcpDsInitDS"
    remap "__imp_DhcpDsGetRoot" "__imp_dsauth$DhcpDsGetRoot"
    remap "__imp_DhcpDsGetLists" "__imp_dsauth$DhcpDsGetLists"
    remap "__imp_DhcpDsGetAttribs" "__imp_dsauth$DhcpDsGetAttribs"
    remap "__imp_DhcpDsEnumServers" "__imp_dsauth$DhcpDsEnumServers"
    remap "__imp_DhcpDsDelServer" "__imp_dsauth$DhcpDsDelServer"
    remap "__imp_DhcpDsCleanupDS" "__imp_dsauth$DhcpDsCleanupDS"
    remap "__imp_DhcpDsAddServer" "__imp_dsauth$DhcpDsAddServer"
    remap "__imp_DhcpDeleteServerDS" "__imp_dsauth$DhcpDeleteServerDS"
    remap "__imp_DhcpAddServerDS" "__imp_dsauth$DhcpAddServerDS"
x86:
