x64:
    remap "__imp_GetDeviceID" "__imp_dsound$GetDeviceID"
    remap "__imp_DllGetClassObject" "__imp_dsound$DllGetClassObject"
    remap "__imp_DllCanUnloadNow" "__imp_dsound$DllCanUnloadNow"
    remap "__imp_DirectSoundFullDuplexCreate" "__imp_dsound$DirectSoundFullDuplexCreate"
    remap "__imp_DirectSoundEnumerateW" "__imp_dsound$DirectSoundEnumerateW"
    remap "__imp_DirectSoundEnumerateA" "__imp_dsound$DirectSoundEnumerateA"
    remap "__imp_DirectSoundCreate8" "__imp_dsound$DirectSoundCreate8"
    remap "__imp_DirectSoundCreate" "__imp_dsound$DirectSoundCreate"
    remap "__imp_DirectSoundCaptureEnumerateW" "__imp_dsound$DirectSoundCaptureEnumerateW"
    remap "__imp_DirectSoundCaptureEnumerateA" "__imp_dsound$DirectSoundCaptureEnumerateA"
    remap "__imp_DirectSoundCaptureCreate8" "__imp_dsound$DirectSoundCaptureCreate8"
    remap "__imp_DirectSoundCaptureCreate" "__imp_dsound$DirectSoundCaptureCreate"
x86:
    remap "__imp__GetDeviceID@8" "__imp__dsound$GetDeviceID@8"
    remap "__imp__DirectSoundFullDuplexCreate@40" "__imp__dsound$DirectSoundFullDuplexCreate@40"
    remap "__imp__DirectSoundEnumerateW@8" "__imp__dsound$DirectSoundEnumerateW@8"
    remap "__imp__DirectSoundEnumerateA@8" "__imp__dsound$DirectSoundEnumerateA@8"
    remap "__imp__DirectSoundCreate@12" "__imp__dsound$DirectSoundCreate@12"
    remap "__imp__DirectSoundCreate8@12" "__imp__dsound$DirectSoundCreate8@12"
    remap "__imp__DirectSoundCaptureEnumerateW@8" "__imp__dsound$DirectSoundCaptureEnumerateW@8"
    remap "__imp__DirectSoundCaptureEnumerateA@8" "__imp__dsound$DirectSoundCaptureEnumerateA@8"
    remap "__imp__DirectSoundCaptureCreate@12" "__imp__dsound$DirectSoundCaptureCreate@12"
    remap "__imp__DirectSoundCaptureCreate8@12" "__imp__dsound$DirectSoundCaptureCreate8@12"
