# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_Smart_PADS_ATTR_INFO__Empty" "__imp_dsprop$Smart_PADS_ATTR_INFO__Empty"
    remap "__imp_ReportError" "__imp_dsprop$ReportError"
    remap "__imp_PostADsPropSheet" "__imp_dsprop$PostADsPropSheet"
    remap "__imp_MsgBox" "__imp_dsprop$MsgBox"
    remap "__imp_IsSheetAlreadyUp" "__imp_dsprop$IsSheetAlreadyUp"
    remap "__imp_FindSheet" "__imp_dsprop$FindSheet"
    remap "__imp_ErrMsgParam" "__imp_dsprop$ErrMsgParam"
    remap "__imp_ErrMsg" "__imp_dsprop$ErrMsg"
    remap "__imp_DllUnregisterServer" "__imp_dsprop$DllUnregisterServer"
    remap "__imp_DllRegisterServer" "__imp_dsprop$DllRegisterServer"
    remap "__imp_DllGetClassObject" "__imp_dsprop$DllGetClassObject"
    remap "__imp_DllCanUnloadNow" "__imp_dsprop$DllCanUnloadNow"
    remap "__imp_DSPROP_GetGCSearchOnDomain" "__imp_dsprop$DSPROP_GetGCSearchOnDomain"
    remap "__imp_CrackName" "__imp_dsprop$CrackName"
    remap "__imp_CheckADsError" "__imp_dsprop$CheckADsError"
    remap "__imp_BringSheetToForeground" "__imp_dsprop$BringSheetToForeground"
    remap "__imp_ADsPropShowErrorDialog" "__imp_dsprop$ADsPropShowErrorDialog"
    remap "__imp_ADsPropSetHwndWithTitle" "__imp_dsprop$ADsPropSetHwndWithTitle"
    remap "__imp_ADsPropSetHwnd" "__imp_dsprop$ADsPropSetHwnd"
    remap "__imp_ADsPropSendErrorMessage" "__imp_dsprop$ADsPropSendErrorMessage"
    remap "__imp_ADsPropGetInitInfo" "__imp_dsprop$ADsPropGetInitInfo"
    remap "__imp_ADsPropCreateNotifyObj" "__imp_dsprop$ADsPropCreateNotifyObj"
    remap "__imp_ADsPropCheckIfWritable" "__imp_dsprop$ADsPropCheckIfWritable"
x86:
