x64:
    remap "__imp_DwmpEnableDDASupport" "__imp_dcomp$DwmpEnableDDASupport"
    remap "__imp_DwmFlush" "__imp_dcomp$DwmFlush"
    remap "__imp_DwmEnableMMCSS" "__imp_dcomp$DwmEnableMMCSS"
    remap "__imp_DllGetClassObject" "__imp_dcomp$DllGetClassObject"
    remap "__imp_DllGetActivationFactory" "__imp_dcomp$DllGetActivationFactory"
    remap "__imp_DllCanUnloadNow" "__imp_dcomp$DllCanUnloadNow"
    remap "__imp_DCompositionCreateSurfaceHandle" "__imp_dcomp$DCompositionCreateSurfaceHandle"
    remap "__imp_DCompositionCreateDevice3" "__imp_dcomp$DCompositionCreateDevice3"
    remap "__imp_DCompositionCreateDevice2" "__imp_dcomp$DCompositionCreateDevice2"
    remap "__imp_DCompositionCreateDevice" "__imp_dcomp$DCompositionCreateDevice"
    remap "__imp_DCompositionAttachMouseWheelToHwnd" "__imp_dcomp$DCompositionAttachMouseWheelToHwnd"
    remap "__imp_DCompositionAttachMouseDragToHwnd" "__imp_dcomp$DCompositionAttachMouseDragToHwnd"
x86:
    remap "__imp__DwmpEnableDDASupport" "__imp__dcomp$DwmpEnableDDASupport"
    remap "__imp__DwmFlush" "__imp__dcomp$DwmFlush"
    remap "__imp__DwmEnableMMCSS@4" "__imp__dcomp$DwmEnableMMCSS@4"
    remap "__imp__DllGetClassObject@12" "__imp__dcomp$DllGetClassObject@12"
    remap "__imp__DllGetActivationFactory@8" "__imp__dcomp$DllGetActivationFactory@8"
    remap "__imp__DllCanUnloadNow" "__imp__dcomp$DllCanUnloadNow"
    remap "__imp__DCompositionCreateSurfaceHandle@12" "__imp__dcomp$DCompositionCreateSurfaceHandle@12"
    remap "__imp__DCompositionCreateDevice@12" "__imp__dcomp$DCompositionCreateDevice@12"
    remap "__imp__DCompositionCreateDevice3@12" "__imp__dcomp$DCompositionCreateDevice3@12"
    remap "__imp__DCompositionCreateDevice2@12" "__imp__dcomp$DCompositionCreateDevice2@12"
    remap "__imp__DCompositionAttachMouseWheelToHwnd@12" "__imp__dcomp$DCompositionAttachMouseWheelToHwnd@12"
    remap "__imp__DCompositionAttachMouseDragToHwnd@12" "__imp__dcomp$DCompositionAttachMouseDragToHwnd@12"
