# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_TermSessionEx" "__imp_dbnetlib$TermSessionEx"
    remap "__imp_TermSession" "__imp_dbnetlib$TermSession"
    remap "__imp_TermSSPIPackage" "__imp_dbnetlib$TermSSPIPackage"
    remap "__imp_InitSessionEx" "__imp_dbnetlib$InitSessionEx"
    remap "__imp_InitSession" "__imp_dbnetlib$InitSession"
    remap "__imp_InitSSPIPackage" "__imp_dbnetlib$InitSSPIPackage"
    remap "__imp_InitEnumServers" "__imp_dbnetlib$InitEnumServers"
    remap "__imp_GetNextEnumeration" "__imp_dbnetlib$GetNextEnumeration"
    remap "__imp_GenClientContextEx" "__imp_dbnetlib$GenClientContextEx"
    remap "__imp_GenClientContext" "__imp_dbnetlib$GenClientContext"
    remap "__imp_ConnectionWriteOOB" "__imp_dbnetlib$ConnectionWriteOOB"
    remap "__imp_ConnectionWrite" "__imp_dbnetlib$ConnectionWrite"
    remap "__imp_ConnectionVer" "__imp_dbnetlib$ConnectionVer"
    remap "__imp_ConnectionTransact" "__imp_dbnetlib$ConnectionTransact"
    remap "__imp_ConnectionStatus" "__imp_dbnetlib$ConnectionStatus"
    remap "__imp_ConnectionSqlVer" "__imp_dbnetlib$ConnectionSqlVer"
    remap "__imp_ConnectionServerEnumW" "__imp_dbnetlib$ConnectionServerEnumW"
    remap "__imp_ConnectionServerEnum" "__imp_dbnetlib$ConnectionServerEnum"
    remap "__imp_ConnectionRead" "__imp_dbnetlib$ConnectionRead"
    remap "__imp_ConnectionOption" "__imp_dbnetlib$ConnectionOption"
    remap "__imp_ConnectionOpenW" "__imp_dbnetlib$ConnectionOpenW"
    remap "__imp_ConnectionOpen" "__imp_dbnetlib$ConnectionOpen"
    remap "__imp_ConnectionObjectSize" "__imp_dbnetlib$ConnectionObjectSize"
    remap "__imp_ConnectionMode" "__imp_dbnetlib$ConnectionMode"
    remap "__imp_ConnectionGetSvrUser" "__imp_dbnetlib$ConnectionGetSvrUser"
    remap "__imp_ConnectionFlushCache" "__imp_dbnetlib$ConnectionFlushCache"
    remap "__imp_ConnectionErrorW" "__imp_dbnetlib$ConnectionErrorW"
    remap "__imp_ConnectionError" "__imp_dbnetlib$ConnectionError"
    remap "__imp_ConnectionClose" "__imp_dbnetlib$ConnectionClose"
    remap "__imp_ConnectionCheckForData" "__imp_dbnetlib$ConnectionCheckForData"
    remap "__imp_CloseEnumServers" "__imp_dbnetlib$CloseEnumServers"
x86:
