# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_ord_16" "__imp_d3d9$ord_16"
    remap "__imp_PSGPSampleTexture" "__imp_d3d9$PSGPSampleTexture"
    remap "__imp_PSGPError" "__imp_d3d9$PSGPError"
    remap "__imp_Direct3DShaderValidatorCreate9" "__imp_d3d9$Direct3DShaderValidatorCreate9"
    remap "__imp_Direct3DCreate9Ex" "__imp_d3d9$Direct3DCreate9Ex"
    remap "__imp_Direct3DCreate9" "__imp_d3d9$Direct3DCreate9"
    remap "__imp_Direct3D9EnableMaximizedWindowedModeShim" "__imp_d3d9$Direct3D9EnableMaximizedWindowedModeShim"
    remap "__imp_DebugSetMute" "__imp_d3d9$DebugSetMute"
    remap "__imp_DebugSetLevel" "__imp_d3d9$DebugSetLevel"
    remap "__imp_D3DPERF_SetRegion" "__imp_d3d9$D3DPERF_SetRegion"
    remap "__imp_D3DPERF_SetOptions" "__imp_d3d9$D3DPERF_SetOptions"
    remap "__imp_D3DPERF_SetMarker" "__imp_d3d9$D3DPERF_SetMarker"
    remap "__imp_D3DPERF_QueryRepeatFrame" "__imp_d3d9$D3DPERF_QueryRepeatFrame"
    remap "__imp_D3DPERF_GetStatus" "__imp_d3d9$D3DPERF_GetStatus"
    remap "__imp_D3DPERF_EndEvent" "__imp_d3d9$D3DPERF_EndEvent"
    remap "__imp_D3DPERF_BeginEvent" "__imp_d3d9$D3DPERF_BeginEvent"
x86:
    remap "__imp__Direct3DShaderValidatorCreate9@0" "__imp__d3d9$Direct3DShaderValidatorCreate9@0"
    remap "__imp__Direct3DCreate9Ex@8" "__imp__d3d9$Direct3DCreate9Ex@8"
    remap "__imp__Direct3DCreate9@4" "__imp__d3d9$Direct3DCreate9@4"
    remap "__imp__D3DPERF_SetRegion@8" "__imp__d3d9$D3DPERF_SetRegion@8"
    remap "__imp__D3DPERF_SetOptions@4" "__imp__d3d9$D3DPERF_SetOptions@4"
    remap "__imp__D3DPERF_SetMarker@8" "__imp__d3d9$D3DPERF_SetMarker@8"
    remap "__imp__D3DPERF_QueryRepeatFrame@0" "__imp__d3d9$D3DPERF_QueryRepeatFrame@0"
    remap "__imp__D3DPERF_GetStatus@0" "__imp__d3d9$D3DPERF_GetStatus@0"
    remap "__imp__D3DPERF_EndEvent@0" "__imp__d3d9$D3DPERF_EndEvent@0"
    remap "__imp__D3DPERF_BeginEvent@8" "__imp__d3d9$D3DPERF_BeginEvent@8"
