# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_EapHostPeerQueryUserBlobFromCredentialInputFields" "__imp_eappcfg$EapHostPeerQueryUserBlobFromCredentialInputFields"
    remap "__imp_EapHostPeerQueryUIBlobFromInteractiveUIInputFields" "__imp_eappcfg$EapHostPeerQueryUIBlobFromInteractiveUIInputFields"
    remap "__imp_EapHostPeerQueryInteractiveUIInputFields" "__imp_eappcfg$EapHostPeerQueryInteractiveUIInputFields"
    remap "__imp_EapHostPeerQueryCredentialInputFields" "__imp_eappcfg$EapHostPeerQueryCredentialInputFields"
    remap "__imp_EapHostPeerInvokeInteractiveUI" "__imp_eappcfg$EapHostPeerInvokeInteractiveUI"
    remap "__imp_EapHostPeerInvokeIdentityUI" "__imp_eappcfg$EapHostPeerInvokeIdentityUI"
    remap "__imp_EapHostPeerInvokeConfigUI" "__imp_eappcfg$EapHostPeerInvokeConfigUI"
    remap "__imp_EapHostPeerGetMethods" "__imp_eappcfg$EapHostPeerGetMethods"
    remap "__imp_EapHostPeerGetMethodProperties" "__imp_eappcfg$EapHostPeerGetMethodProperties"
    remap "__imp_EapHostPeerFreeMemory" "__imp_eappcfg$EapHostPeerFreeMemory"
    remap "__imp_EapHostPeerFreeErrorMemory" "__imp_eappcfg$EapHostPeerFreeErrorMemory"
    remap "__imp_EapHostPeerCredentialsXml2Blob" "__imp_eappcfg$EapHostPeerCredentialsXml2Blob"
    remap "__imp_EapHostPeerCreateMethodConfiguration" "__imp_eappcfg$EapHostPeerCreateMethodConfiguration"
    remap "__imp_EapHostPeerConfigXml2Blob" "__imp_eappcfg$EapHostPeerConfigXml2Blob"
    remap "__imp_EapHostPeerConfigBlob2Xml" "__imp_eappcfg$EapHostPeerConfigBlob2Xml"
x86:
    remap "__imp__EapHostPeerQueryUserBlobFromCredentialInputFields@48" "__imp__eappcfg$EapHostPeerQueryUserBlobFromCredentialInputFields@48"
    remap "__imp__EapHostPeerQueryUIBlobFromInteractiveUIInputFields@36" "__imp__eappcfg$EapHostPeerQueryUIBlobFromInteractiveUIInputFields@36"
    remap "__imp__EapHostPeerQueryInteractiveUIInputFields@28" "__imp__eappcfg$EapHostPeerQueryInteractiveUIInputFields@28"
    remap "__imp__EapHostPeerQueryCredentialInputFields@40" "__imp__eappcfg$EapHostPeerQueryCredentialInputFields@40"
    remap "__imp__EapHostPeerInvokeInteractiveUI@24" "__imp__eappcfg$EapHostPeerInvokeInteractiveUI@24"
    remap "__imp__EapHostPeerInvokeIdentityUI@64" "__imp__eappcfg$EapHostPeerInvokeIdentityUI@64"
    remap "__imp__EapHostPeerInvokeConfigUI@44" "__imp__eappcfg$EapHostPeerInvokeConfigUI@44"
    remap "__imp__EapHostPeerGetMethods@8" "__imp__eappcfg$EapHostPeerGetMethods@8"
    remap "__imp__EapHostPeerFreeMemory@4" "__imp__eappcfg$EapHostPeerFreeMemory@4"
    remap "__imp__EapHostPeerFreeErrorMemory@4" "__imp__eappcfg$EapHostPeerFreeErrorMemory@4"
    remap "__imp__EapHostPeerCredentialsXml2Blob@32" "__imp__eappcfg$EapHostPeerCredentialsXml2Blob@32"
    remap "__imp__EapHostPeerConfigXml2Blob@24" "__imp__eappcfg$EapHostPeerConfigXml2Blob@24"
    remap "__imp__EapHostPeerConfigBlob2Xml@36" "__imp__eappcfg$EapHostPeerConfigBlob2Xml@36"
