# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_SetLabel" "__imp_fmifs$SetLabel"
    remap "__imp_QuerySupportedMedia" "__imp_fmifs$QuerySupportedMedia"
    remap "__imp_QueryLatestFileSystemVersion" "__imp_fmifs$QueryLatestFileSystemVersion"
    remap "__imp_QueryIsDiskCheckScheduledForNextBoot" "__imp_fmifs$QueryIsDiskCheckScheduledForNextBoot"
    remap "__imp_QueryFileSystemName" "__imp_fmifs$QueryFileSystemName"
    remap "__imp_QueryDeviceInformationByHandle" "__imp_fmifs$QueryDeviceInformationByHandle"
    remap "__imp_QueryDeviceInformation" "__imp_fmifs$QueryDeviceInformation"
    remap "__imp_QueryCorruptionStateByHandle" "__imp_fmifs$QueryCorruptionStateByHandle"
    remap "__imp_QueryCorruptionState" "__imp_fmifs$QueryCorruptionState"
    remap "__imp_QueryAvailableFileSystemFormat" "__imp_fmifs$QueryAvailableFileSystemFormat"
    remap "__imp_GetNextCorruptionInfo" "__imp_fmifs$GetNextCorruptionInfo"
    remap "__imp_GetFirstCorruptionInfo" "__imp_fmifs$GetFirstCorruptionInfo"
    remap "__imp_GetDefaultFileSystem" "__imp_fmifs$GetDefaultFileSystem"
    remap "__imp_GetCorruptionInfoClose" "__imp_fmifs$GetCorruptionInfoClose"
    remap "__imp_FreeCorruptionInfo" "__imp_fmifs$FreeCorruptionInfo"
    remap "__imp_FormatEx2" "__imp_fmifs$FormatEx2"
    remap "__imp_FormatEx" "__imp_fmifs$FormatEx"
    remap "__imp_Format" "__imp_fmifs$Format"
    remap "__imp_Extend" "__imp_fmifs$Extend"
    remap "__imp_EnableVolumeIntegrity" "__imp_fmifs$EnableVolumeIntegrity"
    remap "__imp_EnableVolumeCompression" "__imp_fmifs$EnableVolumeCompression"
    remap "__imp_DiskCopy" "__imp_fmifs$DiskCopy"
    remap "__imp_ComputeFmMediaType" "__imp_fmifs$ComputeFmMediaType"
    remap "__imp_ChkdskEx" "__imp_fmifs$ChkdskEx"
    remap "__imp_Chkdsk" "__imp_fmifs$Chkdsk"
x86:
