# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_ScrRegGPOListToWbem" "__imp_gptext$ScrRegGPOListToWbem"
    remap "__imp_ProcessWIRELESSPolicyEx" "__imp_gptext$ProcessWIRELESSPolicyEx"
    remap "__imp_ProcessScriptsGroupPolicyEx" "__imp_gptext$ProcessScriptsGroupPolicyEx"
    remap "__imp_ProcessScriptsGroupPolicy" "__imp_gptext$ProcessScriptsGroupPolicy"
    remap "__imp_ProcessPSCHEDPolicy" "__imp_gptext$ProcessPSCHEDPolicy"
    remap "__imp_ProcessIPSECPolicyEx" "__imp_gptext$ProcessIPSECPolicyEx"
    remap "__imp_GenerateWIRELESSPolicy" "__imp_gptext$GenerateWIRELESSPolicy"
    remap "__imp_GenerateScriptsGroupPolicy" "__imp_gptext$GenerateScriptsGroupPolicy"
    remap "__imp_GenerateIPSECPolicy" "__imp_gptext$GenerateIPSECPolicy"
    remap "__imp_DllUnregisterServer" "__imp_gptext$DllUnregisterServer"
    remap "__imp_DllRegisterServer" "__imp_gptext$DllRegisterServer"
    remap "__imp_DllGetClassObject" "__imp_gptext$DllGetClassObject"
    remap "__imp_DllCanUnloadNow" "__imp_gptext$DllCanUnloadNow"
x86:
    remap "__imp__ProcessPSCHEDPolicy@32" "__imp__gptext$ProcessPSCHEDPolicy@32"
    remap "__imp__ProcessEQoSPolicy@32" "__imp__gptext$ProcessEQoSPolicy@32"
    remap "__imp__DllUnregisterServer" "__imp__gptext$DllUnregisterServer"
    remap "__imp__DllRegisterServer" "__imp__gptext$DllRegisterServer"
