x64:
    remap "__imp_ProcessGroupPolicyForZoneMap" "__imp_iedkcs32$ProcessGroupPolicyForZoneMap"
    remap "__imp_ProcessGroupPolicyEx" "__imp_iedkcs32$ProcessGroupPolicyEx"
    remap "__imp_ProcessGroupPolicy" "__imp_iedkcs32$ProcessGroupPolicy"
    remap "__imp_InternetInitializeAutoProxyDll" "__imp_iedkcs32$InternetInitializeAutoProxyDll"
    remap "__imp_GenerateGroupPolicy" "__imp_iedkcs32$GenerateGroupPolicy"
    remap "__imp_DllUnregisterServer" "__imp_iedkcs32$DllUnregisterServer"
    remap "__imp_DllRegisterServer" "__imp_iedkcs32$DllRegisterServer"
    remap "__imp_CloseRASConnections" "__imp_iedkcs32$CloseRASConnections"
    remap "__imp_Clear" "__imp_iedkcs32$Clear"
    remap "__imp_BrandMe" "__imp_iedkcs32$BrandMe"
    remap "__imp_BrandIntra" "__imp_iedkcs32$BrandIntra"
    remap "__imp_BrandInternetExplorer" "__imp_iedkcs32$BrandInternetExplorer"
    remap "__imp_BrandInfAndOutlookExpress" "__imp_iedkcs32$BrandInfAndOutlookExpress"
    remap "__imp_BrandIE4" "__imp_iedkcs32$BrandIE4"
    remap "__imp_BrandICW2" "__imp_iedkcs32$BrandICW2"
    remap "__imp_BrandICW" "__imp_iedkcs32$BrandICW"
    remap "__imp_BrandExternal" "__imp_iedkcs32$BrandExternal"
    remap "__imp_BrandCleanInstallStubs" "__imp_iedkcs32$BrandCleanInstallStubs"
x86:
