# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_CMTranslateRGBsExt" "__imp_icm32$CMTranslateRGBsExt"
    remap "__imp_CMTranslateRGBs" "__imp_icm32$CMTranslateRGBs"
    remap "__imp_CMTranslateRGB" "__imp_icm32$CMTranslateRGB"
    remap "__imp_CMTranslateColors" "__imp_icm32$CMTranslateColors"
    remap "__imp_CMIsProfileValid" "__imp_icm32$CMIsProfileValid"
    remap "__imp_CMGetNamedProfileInfo" "__imp_icm32$CMGetNamedProfileInfo"
    remap "__imp_CMGetInfo" "__imp_icm32$CMGetInfo"
    remap "__imp_CMDeleteTransform" "__imp_icm32$CMDeleteTransform"
    remap "__imp_CMCreateTransformW" "__imp_icm32$CMCreateTransformW"
    remap "__imp_CMCreateTransformExtW" "__imp_icm32$CMCreateTransformExtW"
    remap "__imp_CMCreateTransformExt" "__imp_icm32$CMCreateTransformExt"
    remap "__imp_CMCreateTransform" "__imp_icm32$CMCreateTransform"
    remap "__imp_CMCreateProfileW" "__imp_icm32$CMCreateProfileW"
    remap "__imp_CMCreateProfile" "__imp_icm32$CMCreateProfile"
    remap "__imp_CMCreateMultiProfileTransform" "__imp_icm32$CMCreateMultiProfileTransform"
    remap "__imp_CMCreateDeviceLinkProfile" "__imp_icm32$CMCreateDeviceLinkProfile"
    remap "__imp_CMConvertIndexToColorName" "__imp_icm32$CMConvertIndexToColorName"
    remap "__imp_CMConvertColorNameToIndex" "__imp_icm32$CMConvertColorNameToIndex"
    remap "__imp_CMCheckRGBs" "__imp_icm32$CMCheckRGBs"
    remap "__imp_CMCheckColorsInGamut" "__imp_icm32$CMCheckColorsInGamut"
    remap "__imp_CMCheckColors" "__imp_icm32$CMCheckColors"
x86:
