# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_ord_116" "__imp_input$ord_116"
    remap "__imp_ord_115" "__imp_input$ord_115"
    remap "__imp_ord_103" "__imp_input$ord_103"
    remap "__imp_ord_102" "__imp_input$ord_102"
    remap "__imp_SetDefaultLayoutOrTip" "__imp_input$SetDefaultLayoutOrTip"
    remap "__imp_SaveSystemAcctInputSettings" "__imp_input$SaveSystemAcctInputSettings"
    remap "__imp_SaveDefaultUserInputSettings" "__imp_input$SaveDefaultUserInputSettings"
    remap "__imp_QueryLayoutOrTipStringUserReg" "__imp_input$QueryLayoutOrTipStringUserReg"
    remap "__imp_QueryLayoutOrTipString" "__imp_input$QueryLayoutOrTipString"
    remap "__imp_InstallLayoutOrTipUserReg" "__imp_input$InstallLayoutOrTipUserReg"
    remap "__imp_InstallLayoutOrTipPrivate" "__imp_input$InstallLayoutOrTipPrivate"
    remap "__imp_InstallLayoutOrTip" "__imp_input$InstallLayoutOrTip"
    remap "__imp_InputDll_DownlevelUninitialize" "__imp_input$InputDll_DownlevelUninitialize"
    remap "__imp_InputDll_DownlevelSetUILanguage" "__imp_input$InputDll_DownlevelSetUILanguage"
    remap "__imp_InputDll_DownlevelInitialize" "__imp_input$InputDll_DownlevelInitialize"
    remap "__imp_InputDll_DownlevelEnumLayoutOrTipForSetup" "__imp_input$InputDll_DownlevelEnumLayoutOrTipForSetup"
    remap "__imp_GetLayoutDescription" "__imp_input$GetLayoutDescription"
    remap "__imp_GetDefaultLayout" "__imp_input$GetDefaultLayout"
    remap "__imp_EnumLayoutOrTipForSetup" "__imp_input$EnumLayoutOrTipForSetup"
    remap "__imp_EnumEnabledLayoutOrTipPrivate" "__imp_input$EnumEnabledLayoutOrTipPrivate"
    remap "__imp_EnumEnabledLayoutOrTip" "__imp_input$EnumEnabledLayoutOrTip"
    remap "__imp_CPlApplet" "__imp_input$CPlApplet"
    remap "__imp_ActivateInputProfile" "__imp_input$ActivateInputProfile"
x86:
