# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_LZStart" "__imp_lz32$LZStart"
    remap "__imp_LZSeek" "__imp_lz32$LZSeek"
    remap "__imp_LZRead" "__imp_lz32$LZRead"
    remap "__imp_LZOpenFileW" "__imp_lz32$LZOpenFileW"
    remap "__imp_LZOpenFileA" "__imp_lz32$LZOpenFileA"
    remap "__imp_LZInit" "__imp_lz32$LZInit"
    remap "__imp_LZDone" "__imp_lz32$LZDone"
    remap "__imp_LZCreateFileW" "__imp_lz32$LZCreateFileW"
    remap "__imp_LZCopy" "__imp_lz32$LZCopy"
    remap "__imp_LZCloseFile" "__imp_lz32$LZCloseFile"
    remap "__imp_LZClose" "__imp_lz32$LZClose"
    remap "__imp_GetExpandedNameW" "__imp_lz32$GetExpandedNameW"
    remap "__imp_GetExpandedNameA" "__imp_lz32$GetExpandedNameA"
    remap "__imp_CopyLZFile" "__imp_lz32$CopyLZFile"
x86:
    remap "__imp__LZStart@0" "__imp__lz32$LZStart@0"
    remap "__imp__LZSeek@12" "__imp__lz32$LZSeek@12"
    remap "__imp__LZRead@12" "__imp__lz32$LZRead@12"
    remap "__imp__LZOpenFileW@12" "__imp__lz32$LZOpenFileW@12"
    remap "__imp__LZOpenFileA@12" "__imp__lz32$LZOpenFileA@12"
    remap "__imp__LZInit@4" "__imp__lz32$LZInit@4"
    remap "__imp__LZDone@0" "__imp__lz32$LZDone@0"
    remap "__imp__LZCopy@8" "__imp__lz32$LZCopy@8"
    remap "__imp__LZClose@4" "__imp__lz32$LZClose@4"
    remap "__imp__GetExpandedNameW@8" "__imp__lz32$GetExpandedNameW@8"
    remap "__imp__GetExpandedNameA@8" "__imp__lz32$GetExpandedNameA@8"
    remap "__imp__CopyLZFile@8" "__imp__lz32$CopyLZFile@8"
