# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_SetNetScheduleAccountInformation" "__imp_mstask$SetNetScheduleAccountInformation"
    remap "__imp_SASetNSAccountInformation" "__imp_mstask$SASetNSAccountInformation"
    remap "__imp_SASetAccountInformation" "__imp_mstask$SASetAccountInformation"
    remap "__imp_SAGetNSAccountInformation" "__imp_mstask$SAGetNSAccountInformation"
    remap "__imp_SAGetAccountInformation" "__imp_mstask$SAGetAccountInformation"
    remap "__imp_NetrJobGetInfo" "__imp_mstask$NetrJobGetInfo"
    remap "__imp_NetrJobEnum" "__imp_mstask$NetrJobEnum"
    remap "__imp_NetrJobDel" "__imp_mstask$NetrJobDel"
    remap "__imp_NetrJobAdd" "__imp_mstask$NetrJobAdd"
    remap "__imp_GetNetScheduleAccountInformation" "__imp_mstask$GetNetScheduleAccountInformation"
    remap "__imp_DllGetClassObject" "__imp_mstask$DllGetClassObject"
    remap "__imp_DllCanUnloadNow" "__imp_mstask$DllCanUnloadNow"
    remap "__imp_ConvertAtJobsToTasks" "__imp_mstask$ConvertAtJobsToTasks"
x86:
    remap "__imp__SetNetScheduleAccountInformation@12" "__imp__mstask$SetNetScheduleAccountInformation@12"
    remap "__imp__SASetNSAccountInformation@12" "__imp__mstask$SASetNSAccountInformation@12"
    remap "__imp__SASetAccountInformation@20" "__imp__mstask$SASetAccountInformation@20"
    remap "__imp__SAGetNSAccountInformation@12" "__imp__mstask$SAGetNSAccountInformation@12"
    remap "__imp__SAGetAccountInformation@16" "__imp__mstask$SAGetAccountInformation@16"
    remap "__imp__NetrJobGetInfo@12" "__imp__mstask$NetrJobGetInfo@12"
    remap "__imp__NetrJobEnum@20" "__imp__mstask$NetrJobEnum@20"
    remap "__imp__NetrJobDel@12" "__imp__mstask$NetrJobDel@12"
    remap "__imp__NetrJobAdd@12" "__imp__mstask$NetrJobAdd@12"
    remap "__imp__GetNetScheduleAccountInformation@12" "__imp__mstask$GetNetScheduleAccountInformation@12"
    remap "__imp__DllGetClassObject@12" "__imp__mstask$DllGetClassObject@12"
    remap "__imp__DllCanUnloadNow@0" "__imp__mstask$DllCanUnloadNow@0"
    remap "__imp__ConvertAtJobsToTasks@0" "__imp__mstask$ConvertAtJobsToTasks@0"
