# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_SpcGetCertFromKey" "__imp_mssign32$SpcGetCertFromKey"
    remap "__imp_SignerTimeStampEx3" "__imp_mssign32$SignerTimeStampEx3"
    remap "__imp_SignerTimeStampEx2" "__imp_mssign32$SignerTimeStampEx2"
    remap "__imp_SignerTimeStampEx" "__imp_mssign32$SignerTimeStampEx"
    remap "__imp_SignerTimeStamp" "__imp_mssign32$SignerTimeStamp"
    remap "__imp_SignerSignEx2" "__imp_mssign32$SignerSignEx2"
    remap "__imp_SignerSignEx" "__imp_mssign32$SignerSignEx"
    remap "__imp_SignerSign" "__imp_mssign32$SignerSign"
    remap "__imp_SignerFreeSignerContext" "__imp_mssign32$SignerFreeSignerContext"
    remap "__imp_SignerCreateTimeStampRequest" "__imp_mssign32$SignerCreateTimeStampRequest"
    remap "__imp_SignerAddTimeStampResponseEx" "__imp_mssign32$SignerAddTimeStampResponseEx"
    remap "__imp_SignerAddTimeStampResponse" "__imp_mssign32$SignerAddTimeStampResponse"
    remap "__imp_SignError" "__imp_mssign32$SignError"
    remap "__imp_PvkPrivateKeySaveToMemoryA" "__imp_mssign32$PvkPrivateKeySaveToMemoryA"
    remap "__imp_PvkPrivateKeySaveToMemory" "__imp_mssign32$PvkPrivateKeySaveToMemory"
    remap "__imp_PvkPrivateKeySaveA" "__imp_mssign32$PvkPrivateKeySaveA"
    remap "__imp_PvkPrivateKeySave" "__imp_mssign32$PvkPrivateKeySave"
    remap "__imp_PvkPrivateKeyReleaseContextA" "__imp_mssign32$PvkPrivateKeyReleaseContextA"
    remap "__imp_PvkPrivateKeyReleaseContext" "__imp_mssign32$PvkPrivateKeyReleaseContext"
    remap "__imp_PvkPrivateKeyLoadFromMemoryA" "__imp_mssign32$PvkPrivateKeyLoadFromMemoryA"
    remap "__imp_PvkPrivateKeyLoadFromMemory" "__imp_mssign32$PvkPrivateKeyLoadFromMemory"
    remap "__imp_PvkPrivateKeyLoadA" "__imp_mssign32$PvkPrivateKeyLoadA"
    remap "__imp_PvkPrivateKeyLoad" "__imp_mssign32$PvkPrivateKeyLoad"
    remap "__imp_PvkPrivateKeyAcquireContextFromMemoryA" "__imp_mssign32$PvkPrivateKeyAcquireContextFromMemoryA"
    remap "__imp_PvkPrivateKeyAcquireContextFromMemory" "__imp_mssign32$PvkPrivateKeyAcquireContextFromMemory"
    remap "__imp_PvkPrivateKeyAcquireContextA" "__imp_mssign32$PvkPrivateKeyAcquireContextA"
    remap "__imp_PvkPrivateKeyAcquireContext" "__imp_mssign32$PvkPrivateKeyAcquireContext"
    remap "__imp_PvkGetCryptProv" "__imp_mssign32$PvkGetCryptProv"
    remap "__imp_PvkFreeCryptProv" "__imp_mssign32$PvkFreeCryptProv"
    remap "__imp_GetCryptProvFromCertEx" "__imp_mssign32$GetCryptProvFromCertEx"
    remap "__imp_GetCryptProvFromCert" "__imp_mssign32$GetCryptProvFromCert"
    remap "__imp_FreeCryptProvFromCertEx" "__imp_mssign32$FreeCryptProvFromCertEx"
    remap "__imp_FreeCryptProvFromCert" "__imp_mssign32$FreeCryptProvFromCert"
x86:
