# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_SpUserModeInitialize" "__imp_msv1_0$SpUserModeInitialize"
    remap "__imp_SpLsaModeInitialize" "__imp_msv1_0$SpLsaModeInitialize"
    remap "__imp_SpInstanceInit" "__imp_msv1_0$SpInstanceInit"
    remap "__imp_SpInitialize" "__imp_msv1_0$SpInitialize"
    remap "__imp_MsvValidateTarget" "__imp_msv1_0$MsvValidateTarget"
    remap "__imp_MsvSamValidate" "__imp_msv1_0$MsvSamValidate"
    remap "__imp_MsvSamLogoff" "__imp_msv1_0$MsvSamLogoff"
    remap "__imp_MsvIsLocalhostAliases" "__imp_msv1_0$MsvIsLocalhostAliases"
    remap "__imp_MsvGetLogonAttemptCount" "__imp_msv1_0$MsvGetLogonAttemptCount"
    remap "__imp_Msv1_0SubAuthenticationPresent" "__imp_msv1_0$Msv1_0SubAuthenticationPresent"
    remap "__imp_Msv1_0ExportSubAuthenticationRoutine" "__imp_msv1_0$Msv1_0ExportSubAuthenticationRoutine"
    remap "__imp_LsaApLogonUserEx2" "__imp_msv1_0$LsaApLogonUserEx2"
    remap "__imp_LsaApLogonTerminated" "__imp_msv1_0$LsaApLogonTerminated"
    remap "__imp_LsaApInitializePackage" "__imp_msv1_0$LsaApInitializePackage"
    remap "__imp_LsaApCallPackageUntrusted" "__imp_msv1_0$LsaApCallPackageUntrusted"
    remap "__imp_LsaApCallPackagePassthrough" "__imp_msv1_0$LsaApCallPackagePassthrough"
    remap "__imp_LsaApCallPackage" "__imp_msv1_0$LsaApCallPackage"
x86:
