# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_ShowShareFolderUIW" "__imp_ntshrui$ShowShareFolderUIW"
    remap "__imp_SharingDialogW" "__imp_ntshrui$SharingDialogW"
    remap "__imp_SharingDialogA" "__imp_ntshrui$SharingDialogA"
    remap "__imp_SharingDialog" "__imp_ntshrui$SharingDialog"
    remap "__imp_SetFolderPermissionsForSharing" "__imp_ntshrui$SetFolderPermissionsForSharing"
    remap "__imp_IsPathSharedW" "__imp_ntshrui$IsPathSharedW"
    remap "__imp_IsPathSharedA" "__imp_ntshrui$IsPathSharedA"
    remap "__imp_IsPathShared" "__imp_ntshrui$IsPathShared"
    remap "__imp_IsFolderPrivateForUser" "__imp_ntshrui$IsFolderPrivateForUser"
    remap "__imp_GetNetResourceFromLocalPathW" "__imp_ntshrui$GetNetResourceFromLocalPathW"
    remap "__imp_GetNetResourceFromLocalPathA" "__imp_ntshrui$GetNetResourceFromLocalPathA"
    remap "__imp_GetNetResourceFromLocalPath" "__imp_ntshrui$GetNetResourceFromLocalPath"
    remap "__imp_GetLocalPathFromNetResourceW" "__imp_ntshrui$GetLocalPathFromNetResourceW"
    remap "__imp_GetLocalPathFromNetResourceA" "__imp_ntshrui$GetLocalPathFromNetResourceA"
    remap "__imp_GetLocalPathFromNetResource" "__imp_ntshrui$GetLocalPathFromNetResource"
    remap "__imp_DllGetClassObject" "__imp_ntshrui$DllGetClassObject"
    remap "__imp_DllCanUnloadNow" "__imp_ntshrui$DllCanUnloadNow"
    remap "__imp_CanShareFolderW" "__imp_ntshrui$CanShareFolderW"
x86:
