# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_UpdateLanaConfigUsingAnswerfile" "__imp_netcfgx$UpdateLanaConfigUsingAnswerfile"
    remap "__imp_SvchostChangeSvchostGroup" "__imp_netcfgx$SvchostChangeSvchostGroup"
    remap "__imp_RasRemoveBindings" "__imp_netcfgx$RasRemoveBindings"
    remap "__imp_RasCountBindings" "__imp_netcfgx$RasCountBindings"
    remap "__imp_RasAddBindings" "__imp_netcfgx$RasAddBindings"
    remap "__imp_NetPropPageProvider" "__imp_netcfgx$NetPropPageProvider"
    remap "__imp_NetClassInstaller" "__imp_netcfgx$NetClassInstaller"
    remap "__imp_NetCfgDiagRepairRegistryBindings" "__imp_netcfgx$NetCfgDiagRepairRegistryBindings"
    remap "__imp_NetCfgDiagFromCommandArgs" "__imp_netcfgx$NetCfgDiagFromCommandArgs"
    remap "__imp_ModemClassCoInstaller" "__imp_netcfgx$ModemClassCoInstaller"
    remap "__imp_LanaCfgFromCommandArgs" "__imp_netcfgx$LanaCfgFromCommandArgs"
    remap "__imp_HrDiAddComponentToINetCfg" "__imp_netcfgx$HrDiAddComponentToINetCfg"
    remap "__imp_DllUnregisterServer" "__imp_netcfgx$DllUnregisterServer"
    remap "__imp_DllRegisterServer" "__imp_netcfgx$DllRegisterServer"
    remap "__imp_DllGetClassObject" "__imp_netcfgx$DllGetClassObject"
    remap "__imp_DllCanUnloadNow" "__imp_netcfgx$DllCanUnloadNow"
    remap "__imp_??4WLBS_REG_PARAMS@@QEAAAEAU0@AEBU0@@Z" "__imp_netcfgx$??4WLBS_REG_PARAMS@@QEAAAEAU0@AEBU0@@Z"
x86:
