# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_StartNCW" "__imp_netshell$StartNCW"
    remap "__imp_RepairConnection" "__imp_netshell$RepairConnection"
    remap "__imp_RaiseSupportDialog" "__imp_netshell$RaiseSupportDialog"
    remap "__imp_NormalizeExtendedStatus" "__imp_netshell$NormalizeExtendedStatus"
    remap "__imp_NetSetupSetProgressCallback" "__imp_netshell$NetSetupSetProgressCallback"
    remap "__imp_NetSetupRequestWizardPages" "__imp_netshell$NetSetupRequestWizardPages"
    remap "__imp_NetSetupPrepareSysPrep" "__imp_netshell$NetSetupPrepareSysPrep"
    remap "__imp_NetSetupInstallSoftware" "__imp_netshell$NetSetupInstallSoftware"
    remap "__imp_NetSetupFinishInstall" "__imp_netshell$NetSetupFinishInstall"
    remap "__imp_NetSetupAddRasConnection" "__imp_netshell$NetSetupAddRasConnection"
    remap "__imp_NcIsValidConnectionName" "__imp_netshell$NcIsValidConnectionName"
    remap "__imp_NcFreeNetconProperties" "__imp_netshell$NcFreeNetconProperties"
    remap "__imp_InvokeDunFile" "__imp_netshell$InvokeDunFile"
    remap "__imp_HrRunWizard" "__imp_netshell$HrRunWizard"
    remap "__imp_HrRenameConnection" "__imp_netshell$HrRenameConnection"
    remap "__imp_HrOemUpgrade" "__imp_netshell$HrOemUpgrade"
    remap "__imp_HrLaunchNetworkOptionalComponents" "__imp_netshell$HrLaunchNetworkOptionalComponents"
    remap "__imp_HrLaunchConnectionEx" "__imp_netshell$HrLaunchConnectionEx"
    remap "__imp_HrLaunchConnection" "__imp_netshell$HrLaunchConnection"
    remap "__imp_HrIsIpStateCheckingEnabled" "__imp_netshell$HrIsIpStateCheckingEnabled"
    remap "__imp_HrGetStatusStringFromNetConExtendedStatus" "__imp_netshell$HrGetStatusStringFromNetConExtendedStatus"
    remap "__imp_HrGetNetConExtendedStatusFromINetConnection" "__imp_netshell$HrGetNetConExtendedStatusFromINetConnection"
    remap "__imp_HrGetNetConExtendedStatusFromGuid" "__imp_netshell$HrGetNetConExtendedStatusFromGuid"
    remap "__imp_HrGetInstanceGuidOfPreNT5NetCardInstance" "__imp_netshell$HrGetInstanceGuidOfPreNT5NetCardInstance"
    remap "__imp_HrGetIconFromMediaTypeEx" "__imp_netshell$HrGetIconFromMediaTypeEx"
    remap "__imp_HrGetIconFromMediaType" "__imp_netshell$HrGetIconFromMediaType"
    remap "__imp_HrGetExtendedStatusFromNCS" "__imp_netshell$HrGetExtendedStatusFromNCS"
    remap "__imp_HrGetAnswerFileParametersForNetCard" "__imp_netshell$HrGetAnswerFileParametersForNetCard"
    remap "__imp_HrCreateDesktopIcon" "__imp_netshell$HrCreateDesktopIcon"
    remap "__imp_DoInitialCleanup" "__imp_netshell$DoInitialCleanup"
    remap "__imp_DllUnregisterServer" "__imp_netshell$DllUnregisterServer"
    remap "__imp_DllRegisterServer" "__imp_netshell$DllRegisterServer"
    remap "__imp_DllGetClassObject" "__imp_netshell$DllGetClassObject"
    remap "__imp_DllCanUnloadNow" "__imp_netshell$DllCanUnloadNow"
x86:
