x64:
    remap "__imp_ServiceMain" "__imp_qmgr$ServiceMain"
    remap "__imp_DllUnregisterServer" "__imp_qmgr$DllUnregisterServer"
    remap "__imp_DllRegisterServer" "__imp_qmgr$DllRegisterServer"
    remap "__imp_BITSServiceMain" "__imp_qmgr$BITSServiceMain"
    remap "__imp_?s_EmptyString@?$GenericStringHandle@G@@0UStringData@1@A" "__imp_qmgr$?s_EmptyString@?$GenericStringHandle@G@@0UStringData@1@A"
    remap "__imp_?HostFromProxyDescription@@YA?AV?$auto_ptr@G@std@@PEAG@Z" "__imp_qmgr$?HostFromProxyDescription@@YA?AV?$auto_ptr@G@std@@PEAG@Z"
    remap "__imp_?GetSubRanges@CRangeCollection@@QEAAJ_K00IPEAPEAV1@@Z" "__imp_qmgr$?GetSubRanges@CRangeCollection@@QEAAJ_K00IPEAPEAV1@@Z"
    remap "__imp_?FindInterfaceIndex@@YAKPEBG@Z" "__imp_qmgr$?FindInterfaceIndex@@YAKPEBG@Z"
    remap "__imp_?Find@CCredentialsContainer@@QEBAJW4__MIDL_IBackgroundCopyJob2_0001@@W4__MIDL_IBackgroundCopyJob2_0002@@PEAPEAU__MIDL_IBackgroundCopyJob2_0005@@@Z" "__imp_qmgr$?Find@CCredentialsContainer@@QEBAJW4__MIDL_IBackgroundCopyJob2_0001@@W4__MIDL_IBackgroundCopyJob2_0002@@PEAPEAU__MIDL_IBackgroundCopyJob2_0005@@@Z"
    remap "__imp_?CalculateBytesTotal@CRangeCollection@@IEAA_NXZ" "__imp_qmgr$?CalculateBytesTotal@CRangeCollection@@IEAA_NXZ"
    remap "__imp_?BytesRemainingInCurrentRange@CRangeCollection@@QEAA_KXZ" "__imp_qmgr$?BytesRemainingInCurrentRange@CRangeCollection@@QEAA_KXZ"
    remap "__imp_?BITSFree@@YAXPEAX@Z" "__imp_qmgr$?BITSFree@@YAXPEAX@Z"
    remap "__imp_?BITSAlloc@@YAPEAX_K@Z" "__imp_qmgr$?BITSAlloc@@YAPEAX_K@Z"
    remap "__imp_??0PROXY_SETTINGS_CONTAINER@@QEAA@PEBGPEBUPROXY_SETTINGS@@@Z" "__imp_qmgr$??0PROXY_SETTINGS_CONTAINER@@QEAA@PEBGPEBUPROXY_SETTINGS@@@Z"
    remap "__imp_??0CNestedImpersonation@@QEAA@XZ" "__imp_qmgr$??0CNestedImpersonation@@QEAA@XZ"
    remap "__imp_??0CNestedImpersonation@@QEAA@PEAX@Z" "__imp_qmgr$??0CNestedImpersonation@@QEAA@PEAX@Z"
    remap "__imp_??0CNestedImpersonation@@QEAA@AEAVTokenHandle@@@Z" "__imp_qmgr$??0CNestedImpersonation@@QEAA@AEAVTokenHandle@@@Z"
x86:
