# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_ServiceMain" "__imp_qwave$ServiceMain"
    remap "__imp_QOSStopTrackingClient" "__imp_qwave$QOSStopTrackingClient"
    remap "__imp_QOSStartTrackingClient" "__imp_qwave$QOSStartTrackingClient"
    remap "__imp_QOSSetFlow" "__imp_qwave$QOSSetFlow"
    remap "__imp_QOSRemoveSocketFromFlow" "__imp_qwave$QOSRemoveSocketFromFlow"
    remap "__imp_QOSQueryFlow" "__imp_qwave$QOSQueryFlow"
    remap "__imp_QOSNotifyFlow" "__imp_qwave$QOSNotifyFlow"
    remap "__imp_QOSEnumerateFlows" "__imp_qwave$QOSEnumerateFlows"
    remap "__imp_QOSCreateHandle" "__imp_qwave$QOSCreateHandle"
    remap "__imp_QOSCloseHandle" "__imp_qwave$QOSCloseHandle"
    remap "__imp_QOSCancel" "__imp_qwave$QOSCancel"
    remap "__imp_QOSAddSocketToFlow" "__imp_qwave$QOSAddSocketToFlow"
    remap "__imp_QDLHStartDiagnosingPath" "__imp_qwave$QDLHStartDiagnosingPath"
    remap "__imp_QDLHPathDiagnostics" "__imp_qwave$QDLHPathDiagnostics"
x86:
    remap "__imp__ServiceMain@8" "__imp__qwave$ServiceMain@8"
    remap "__imp__QOSStopTrackingClient@12" "__imp__qwave$QOSStopTrackingClient@12"
    remap "__imp__QOSStartTrackingClient@12" "__imp__qwave$QOSStartTrackingClient@12"
    remap "__imp__QOSSetFlow@28" "__imp__qwave$QOSSetFlow@28"
    remap "__imp__QOSRemoveSocketFromFlow@16" "__imp__qwave$QOSRemoveSocketFromFlow@16"
    remap "__imp__QOSQueryFlow@28" "__imp__qwave$QOSQueryFlow@28"
    remap "__imp__QOSNotifyFlow@28" "__imp__qwave$QOSNotifyFlow@28"
    remap "__imp__QOSEnumerateFlows@12" "__imp__qwave$QOSEnumerateFlows@12"
    remap "__imp__QOSCreateHandle@8" "__imp__qwave$QOSCreateHandle@8"
    remap "__imp__QOSCloseHandle@4" "__imp__qwave$QOSCloseHandle@4"
    remap "__imp__QOSCancel@8" "__imp__qwave$QOSCancel@8"
    remap "__imp__QOSAddSocketToFlow@24" "__imp__qwave$QOSAddSocketToFlow@24"
    remap "__imp__QDLHStartDiagnosingPath@12" "__imp__qwave$QDLHStartDiagnosingPath@12"
    remap "__imp__QDLHPathDiagnostics@20" "__imp__qwave$QDLHPathDiagnostics@20"
