# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_LoadTextFilter" "__imp_query$LoadTextFilter"
    remap "__imp_LoadIFilterEx" "__imp_query$LoadIFilterEx"
    remap "__imp_LoadIFilter" "__imp_query$LoadIFilter"
    remap "__imp_LoadBinaryFilter" "__imp_query$LoadBinaryFilter"
    remap "__imp_DllUnregisterServer" "__imp_query$DllUnregisterServer"
    remap "__imp_DllRegisterServer" "__imp_query$DllRegisterServer"
    remap "__imp_DllGetClassObject" "__imp_query$DllGetClassObject"
    remap "__imp_DllCanUnloadNow" "__imp_query$DllCanUnloadNow"
    remap "__imp_BindIFilterFromStream" "__imp_query$BindIFilterFromStream"
    remap "__imp_BindIFilterFromStorage" "__imp_query$BindIFilterFromStorage"
x86:
    remap "__imp__LoadTextFilter@8" "__imp__query$LoadTextFilter@8"
    remap "__imp__LoadIFilterEx@16" "__imp__query$LoadIFilterEx@16"
    remap "__imp__LoadIFilter@12" "__imp__query$LoadIFilter@12"
    remap "__imp__LoadBinaryFilter@8" "__imp__query$LoadBinaryFilter@8"
    remap "__imp__DllUnregisterServer" "__imp__query$DllUnregisterServer"
    remap "__imp__DllRegisterServer" "__imp__query$DllRegisterServer"
    remap "__imp__DllGetClassObject@12" "__imp__query$DllGetClassObject@12"
    remap "__imp__DllCanUnloadNow" "__imp__query$DllCanUnloadNow"
    remap "__imp__BindIFilterFromStream@12" "__imp__query$BindIFilterFromStream@12"
    remap "__imp__BindIFilterFromStorage@12" "__imp__query$BindIFilterFromStorage@12"
