# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_DllUnregisterServer" "__imp_rsaenh$DllUnregisterServer"
    remap "__imp_DllRegisterServer" "__imp_rsaenh$DllRegisterServer"
    remap "__imp_CPVerifySignature" "__imp_rsaenh$CPVerifySignature"
    remap "__imp_CPSignHash" "__imp_rsaenh$CPSignHash"
    remap "__imp_CPSetProvParam" "__imp_rsaenh$CPSetProvParam"
    remap "__imp_CPSetKeyParam" "__imp_rsaenh$CPSetKeyParam"
    remap "__imp_CPSetHashParam" "__imp_rsaenh$CPSetHashParam"
    remap "__imp_CPReleaseContext" "__imp_rsaenh$CPReleaseContext"
    remap "__imp_CPImportKey" "__imp_rsaenh$CPImportKey"
    remap "__imp_CPHashSessionKey" "__imp_rsaenh$CPHashSessionKey"
    remap "__imp_CPHashData" "__imp_rsaenh$CPHashData"
    remap "__imp_CPGetUserKey" "__imp_rsaenh$CPGetUserKey"
    remap "__imp_CPGetProvParam" "__imp_rsaenh$CPGetProvParam"
    remap "__imp_CPGetKeyParam" "__imp_rsaenh$CPGetKeyParam"
    remap "__imp_CPGetHashParam" "__imp_rsaenh$CPGetHashParam"
    remap "__imp_CPGenRandom" "__imp_rsaenh$CPGenRandom"
    remap "__imp_CPGenKey" "__imp_rsaenh$CPGenKey"
    remap "__imp_CPExportKey" "__imp_rsaenh$CPExportKey"
    remap "__imp_CPEncrypt" "__imp_rsaenh$CPEncrypt"
    remap "__imp_CPDuplicateKey" "__imp_rsaenh$CPDuplicateKey"
    remap "__imp_CPDuplicateHash" "__imp_rsaenh$CPDuplicateHash"
    remap "__imp_CPDestroyKey" "__imp_rsaenh$CPDestroyKey"
    remap "__imp_CPDestroyHash" "__imp_rsaenh$CPDestroyHash"
    remap "__imp_CPDeriveKey" "__imp_rsaenh$CPDeriveKey"
    remap "__imp_CPDecrypt" "__imp_rsaenh$CPDecrypt"
    remap "__imp_CPCreateHash" "__imp_rsaenh$CPCreateHash"
    remap "__imp_CPAcquireContext" "__imp_rsaenh$CPAcquireContext"
x86:
