# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_RasEapQueryUserBlobFromCredentialInputFields" "__imp_raschap$RasEapQueryUserBlobFromCredentialInputFields"
    remap "__imp_RasEapQueryUIBlobFromInteractiveUIInputFields" "__imp_raschap$RasEapQueryUIBlobFromInteractiveUIInputFields"
    remap "__imp_RasEapQueryInteractiveUIInputFields" "__imp_raschap$RasEapQueryInteractiveUIInputFields"
    remap "__imp_RasEapQueryCredentialInputFields" "__imp_raschap$RasEapQueryCredentialInputFields"
    remap "__imp_RasEapInvokeInteractiveUI" "__imp_raschap$RasEapInvokeInteractiveUI"
    remap "__imp_RasEapInvokeConfigUI" "__imp_raschap$RasEapInvokeConfigUI"
    remap "__imp_RasEapGetNextPageGuid" "__imp_raschap$RasEapGetNextPageGuid"
    remap "__imp_RasEapGetMethodProperties" "__imp_raschap$RasEapGetMethodProperties"
    remap "__imp_RasEapGetInfo" "__imp_raschap$RasEapGetInfo"
    remap "__imp_RasEapGetIdentityPageGuid" "__imp_raschap$RasEapGetIdentityPageGuid"
    remap "__imp_RasEapGetIdentity" "__imp_raschap$RasEapGetIdentity"
    remap "__imp_RasEapGetCredentials" "__imp_raschap$RasEapGetCredentials"
    remap "__imp_RasEapGetConfigBlobAndUserBlob" "__imp_raschap$RasEapGetConfigBlobAndUserBlob"
    remap "__imp_RasEapFreeMemory" "__imp_raschap$RasEapFreeMemory"
    remap "__imp_RasEapCreateUserProperties2" "__imp_raschap$RasEapCreateUserProperties2"
    remap "__imp_RasEapCreateUserProperties" "__imp_raschap$RasEapCreateUserProperties"
    remap "__imp_RasEapCreateMethodConfiguration" "__imp_raschap$RasEapCreateMethodConfiguration"
    remap "__imp_RasEapCreateConnectionPropertiesXml" "__imp_raschap$RasEapCreateConnectionPropertiesXml"
    remap "__imp_RasEapCreateConnectionProperties2" "__imp_raschap$RasEapCreateConnectionProperties2"
    remap "__imp_RasEapCreateConnectionProperties" "__imp_raschap$RasEapCreateConnectionProperties"
    remap "__imp_RasCpGetInfo" "__imp_raschap$RasCpGetInfo"
    remap "__imp_RasCpEnumProtocolIds" "__imp_raschap$RasCpEnumProtocolIds"
x86:
