# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_SoftpubLoadSignature" "__imp_softpub$SoftpubLoadSignature"
    remap "__imp_SoftpubLoadMessage" "__imp_softpub$SoftpubLoadMessage"
    remap "__imp_SoftpubLoadDefUsageCallData" "__imp_softpub$SoftpubLoadDefUsageCallData"
    remap "__imp_SoftpubInitialize" "__imp_softpub$SoftpubInitialize"
    remap "__imp_SoftpubFreeDefUsageCallData" "__imp_softpub$SoftpubFreeDefUsageCallData"
    remap "__imp_SoftpubDumpStructure" "__imp_softpub$SoftpubDumpStructure"
    remap "__imp_SoftpubDefCertInit" "__imp_softpub$SoftpubDefCertInit"
    remap "__imp_SoftpubCleanup" "__imp_softpub$SoftpubCleanup"
    remap "__imp_SoftpubCheckCert" "__imp_softpub$SoftpubCheckCert"
    remap "__imp_SoftpubAuthenticode" "__imp_softpub$SoftpubAuthenticode"
    remap "__imp_OpenPersonalTrustDBDialog" "__imp_softpub$OpenPersonalTrustDBDialog"
    remap "__imp_OfficeInitializePolicy" "__imp_softpub$OfficeInitializePolicy"
    remap "__imp_OfficeCleanupPolicy" "__imp_softpub$OfficeCleanupPolicy"
    remap "__imp_HTTPSFinalProv" "__imp_softpub$HTTPSFinalProv"
    remap "__imp_HTTPSCertificateTrust" "__imp_softpub$HTTPSCertificateTrust"
    remap "__imp_GenericChainFinalProv" "__imp_softpub$GenericChainFinalProv"
    remap "__imp_GenericChainCertificateTrust" "__imp_softpub$GenericChainCertificateTrust"
    remap "__imp_FindCertsByIssuer" "__imp_softpub$FindCertsByIssuer"
    remap "__imp_DriverInitializePolicy" "__imp_softpub$DriverInitializePolicy"
    remap "__imp_DriverFinalPolicy" "__imp_softpub$DriverFinalPolicy"
    remap "__imp_DriverCleanupPolicy" "__imp_softpub$DriverCleanupPolicy"
    remap "__imp_DllUnregisterServer" "__imp_softpub$DllUnregisterServer"
    remap "__imp_DllRegisterServer" "__imp_softpub$DllRegisterServer"
    remap "__imp_AddPersonalTrustDBPages" "__imp_softpub$AddPersonalTrustDBPages"
x86:
