# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_SRUpdateMonitoredListW" "__imp_srclient$SRUpdateMonitoredListW"
    remap "__imp_SRUpdateMonitoredListA" "__imp_srclient$SRUpdateMonitoredListA"
    remap "__imp_SRUpdateDSSize" "__imp_srclient$SRUpdateDSSize"
    remap "__imp_SRUnregisterSnapshotCallback" "__imp_srclient$SRUnregisterSnapshotCallback"
    remap "__imp_SRSwitchLog" "__imp_srclient$SRSwitchLog"
    remap "__imp_SRSetRestorePointW" "__imp_srclient$SRSetRestorePointW"
    remap "__imp_SRSetRestorePointA" "__imp_srclient$SRSetRestorePointA"
    remap "__imp_SRRemoveRestorePoint" "__imp_srclient$SRRemoveRestorePoint"
    remap "__imp_SRRegisterSnapshotCallback" "__imp_srclient$SRRegisterSnapshotCallback"
    remap "__imp_SRPrintState" "__imp_srclient$SRPrintState"
    remap "__imp_SRNotify" "__imp_srclient$SRNotify"
    remap "__imp_SRFreeze" "__imp_srclient$SRFreeze"
    remap "__imp_SRFifo" "__imp_srclient$SRFifo"
    remap "__imp_SRCompress" "__imp_srclient$SRCompress"
    remap "__imp_RestoreSnapshot" "__imp_srclient$RestoreSnapshot"
    remap "__imp_ResetSR" "__imp_srclient$ResetSR"
    remap "__imp_EnableSREx" "__imp_srclient$EnableSREx"
    remap "__imp_EnableSR" "__imp_srclient$EnableSR"
    remap "__imp_EnableFIFO" "__imp_srclient$EnableFIFO"
    remap "__imp_DllUnregisterServer" "__imp_srclient$DllUnregisterServer"
    remap "__imp_DllRegisterServer" "__imp_srclient$DllRegisterServer"
    remap "__imp_DllGetClassObject" "__imp_srclient$DllGetClassObject"
    remap "__imp_DllCanUnloadNow" "__imp_srclient$DllCanUnloadNow"
    remap "__imp_DisableSR" "__imp_srclient$DisableSR"
    remap "__imp_DisableFIFO" "__imp_srclient$DisableFIFO"
    remap "__imp_CreateSnapshot" "__imp_srclient$CreateSnapshot"
    remap "__imp_CreateFirstRunRp" "__imp_srclient$CreateFirstRunRp"
x86:
