# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_WiaRemoveDevice" "__imp_sti_ci$WiaRemoveDevice"
    remap "__imp_WiaDestroyPortList" "__imp_sti_ci$WiaDestroyPortList"
    remap "__imp_WiaCreateWizardMenu" "__imp_sti_ci$WiaCreateWizardMenu"
    remap "__imp_WiaCreatePortList" "__imp_sti_ci$WiaCreatePortList"
    remap "__imp_WiaAddDevice" "__imp_sti_ci$WiaAddDevice"
    remap "__imp_PTPCoinstallerEntry" "__imp_sti_ci$PTPCoinstallerEntry"
    remap "__imp_MigrateDevice" "__imp_sti_ci$MigrateDevice"
    remap "__imp_InstallWiaService" "__imp_sti_ci$InstallWiaService"
    remap "__imp_CoinstallerEntry" "__imp_sti_ci$CoinstallerEntry"
    remap "__imp_ClassInstall" "__imp_sti_ci$ClassInstall"
    remap "__imp_AddDevice" "__imp_sti_ci$AddDevice"
    remap "__imp_?SetUsed@BUFFER_CHAIN_ITEM@@QEAAXK@Z" "__imp_sti_ci$?SetUsed@BUFFER_CHAIN_ITEM@@QEAAXK@Z"
    remap "__imp_?QueryUsed@BUFFER_CHAIN_ITEM@@QEBAKXZ" "__imp_sti_ci$?QueryUsed@BUFFER_CHAIN_ITEM@@QEBAKXZ"
    remap "__imp_?QuerySize@BUFFER@@QEBAIXZ" "__imp_sti_ci$?QuerySize@BUFFER@@QEBAIXZ"
    remap "__imp_?QueryPtr@BUFFER@@QEBAPEAXXZ" "__imp_sti_ci$?QueryPtr@BUFFER@@QEBAPEAXXZ"
    remap "__imp_??_FBUFFER_CHAIN_ITEM@@QEAAXXZ" "__imp_sti_ci$??_FBUFFER_CHAIN_ITEM@@QEAAXXZ"
    remap "__imp_??_FBUFFER@@QEAAXXZ" "__imp_sti_ci$??_FBUFFER@@QEAAXXZ"
    remap "__imp_??1BUFFER_CHAIN_ITEM@@QEAA@XZ" "__imp_sti_ci$??1BUFFER_CHAIN_ITEM@@QEAA@XZ"
    remap "__imp_??1BUFFER_CHAIN@@QEAA@XZ" "__imp_sti_ci$??1BUFFER_CHAIN@@QEAA@XZ"
    remap "__imp_??1BUFFER@@QEAA@XZ" "__imp_sti_ci$??1BUFFER@@QEAA@XZ"
    remap "__imp_??0BUFFER_CHAIN_ITEM@@QEAA@I@Z" "__imp_sti_ci$??0BUFFER_CHAIN_ITEM@@QEAA@I@Z"
    remap "__imp_??0BUFFER_CHAIN@@QEAA@XZ" "__imp_sti_ci$??0BUFFER_CHAIN@@QEAA@XZ"
    remap "__imp_??0BUFFER@@QEAA@I@Z" "__imp_sti_ci$??0BUFFER@@QEAA@I@Z"
x86:
