# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_StiCreateInstanceW" "__imp_sti$StiCreateInstanceW"
    remap "__imp_StiCreateInstanceA" "__imp_sti$StiCreateInstanceA"
    remap "__imp_StiCreateInstance" "__imp_sti$StiCreateInstance"
    remap "__imp_RegSTIforWia" "__imp_sti$RegSTIforWia"
    remap "__imp_MigrateRegisteredSTIAppsForWIAEvents" "__imp_sti$MigrateRegisteredSTIAppsForWIAEvents"
    remap "__imp_GetProxyDllInfo" "__imp_sti$GetProxyDllInfo"
    remap "__imp_DllUnregisterServer" "__imp_sti$DllUnregisterServer"
    remap "__imp_DllRegisterServer" "__imp_sti$DllRegisterServer"
    remap "__imp_DllGetClassObject" "__imp_sti$DllGetClassObject"
    remap "__imp_DllCanUnloadNow" "__imp_sti$DllCanUnloadNow"
    remap "__imp_?SetUsed@BUFFER_CHAIN_ITEM@@QEAAXK@Z" "__imp_sti$?SetUsed@BUFFER_CHAIN_ITEM@@QEAAXK@Z"
    remap "__imp_?QueryUsed@BUFFER_CHAIN_ITEM@@QEBAKXZ" "__imp_sti$?QueryUsed@BUFFER_CHAIN_ITEM@@QEBAKXZ"
    remap "__imp_?QuerySize@BUFFER@@QEBAIXZ" "__imp_sti$?QuerySize@BUFFER@@QEBAIXZ"
    remap "__imp_?QueryPtr@BUFFER@@QEBAPEAXXZ" "__imp_sti$?QueryPtr@BUFFER@@QEBAPEAXXZ"
    remap "__imp_??_FBUFFER_CHAIN_ITEM@@QEAAXXZ" "__imp_sti$??_FBUFFER_CHAIN_ITEM@@QEAAXXZ"
    remap "__imp_??_FBUFFER@@QEAAXXZ" "__imp_sti$??_FBUFFER@@QEAAXXZ"
    remap "__imp_??1BUFFER_CHAIN_ITEM@@QEAA@XZ" "__imp_sti$??1BUFFER_CHAIN_ITEM@@QEAA@XZ"
    remap "__imp_??1BUFFER_CHAIN@@QEAA@XZ" "__imp_sti$??1BUFFER_CHAIN@@QEAA@XZ"
    remap "__imp_??1BUFFER@@QEAA@XZ" "__imp_sti$??1BUFFER@@QEAA@XZ"
    remap "__imp_??0BUFFER_CHAIN_ITEM@@QEAA@I@Z" "__imp_sti$??0BUFFER_CHAIN_ITEM@@QEAA@I@Z"
    remap "__imp_??0BUFFER_CHAIN@@QEAA@XZ" "__imp_sti$??0BUFFER_CHAIN@@QEAA@XZ"
    remap "__imp_??0BUFFER@@QEAA@I@Z" "__imp_sti$??0BUFFER@@QEAA@I@Z"
x86:
