# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_TTRunValidationTestsEx" "__imp_t2embed$TTRunValidationTestsEx"
    remap "__imp_TTRunValidationTests" "__imp_t2embed$TTRunValidationTests"
    remap "__imp_TTLoadEmbeddedFont" "__imp_t2embed$TTLoadEmbeddedFont"
    remap "__imp_TTIsEmbeddingEnabledForFacename" "__imp_t2embed$TTIsEmbeddingEnabledForFacename"
    remap "__imp_TTIsEmbeddingEnabled" "__imp_t2embed$TTIsEmbeddingEnabled"
    remap "__imp_TTGetNewFontName" "__imp_t2embed$TTGetNewFontName"
    remap "__imp_TTGetEmbeddingType" "__imp_t2embed$TTGetEmbeddingType"
    remap "__imp_TTGetEmbeddedFontInfo" "__imp_t2embed$TTGetEmbeddedFontInfo"
    remap "__imp_TTEnableEmbeddingForFacename" "__imp_t2embed$TTEnableEmbeddingForFacename"
    remap "__imp_TTEmbedFontFromFileA" "__imp_t2embed$TTEmbedFontFromFileA"
    remap "__imp_TTEmbedFontEx" "__imp_t2embed$TTEmbedFontEx"
    remap "__imp_TTEmbedFont" "__imp_t2embed$TTEmbedFont"
    remap "__imp_TTDeleteEmbeddedFont" "__imp_t2embed$TTDeleteEmbeddedFont"
    remap "__imp_TTCharToUnicode" "__imp_t2embed$TTCharToUnicode"
x86:
    remap "__imp__TTRunValidationTestsEx@8" "__imp__t2embed$TTRunValidationTestsEx@8"
    remap "__imp__TTRunValidationTests@8" "__imp__t2embed$TTRunValidationTests@8"
    remap "__imp__TTLoadEmbeddedFont@40" "__imp__t2embed$TTLoadEmbeddedFont@40"
    remap "__imp__TTIsEmbeddingEnabledForFacename@8" "__imp__t2embed$TTIsEmbeddingEnabledForFacename@8"
    remap "__imp__TTIsEmbeddingEnabled@8" "__imp__t2embed$TTIsEmbeddingEnabled@8"
    remap "__imp__TTGetNewFontName@20" "__imp__t2embed$TTGetNewFontName@20"
    remap "__imp__TTGetEmbeddingType@8" "__imp__t2embed$TTGetEmbeddingType@8"
    remap "__imp__TTGetEmbeddedFontInfo@28" "__imp__t2embed$TTGetEmbeddedFontInfo@28"
    remap "__imp__TTEnableEmbeddingForFacename@8" "__imp__t2embed$TTEnableEmbeddingForFacename@8"
    remap "__imp__TTEmbedFontFromFileA@52" "__imp__t2embed$TTEmbedFontFromFileA@52"
    remap "__imp__TTEmbedFontEx@44" "__imp__t2embed$TTEmbedFontEx@44"
    remap "__imp__TTEmbedFont@44" "__imp__t2embed$TTEmbedFont@44"
    remap "__imp__TTDeleteEmbeddedFont@12" "__imp__t2embed$TTDeleteEmbeddedFont@12"
    remap "__imp__TTCharToUnicode@24" "__imp__t2embed$TTCharToUnicode@24"
