# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_Ping" "__imp_tcpmib$Ping"
    remap "__imp_GetTcpMibPtr" "__imp_tcpmib$GetTcpMibPtr"
    remap "__imp_?UnInitSnmp@CTcpMib@@UEAAXXZ" "__imp_tcpmib$?UnInitSnmp@CTcpMib@@UEAAXXZ"
    remap "__imp_?SupportsPrinterMib@CTcpMib@@UEAAHPEBD0KPEAH@Z" "__imp_tcpmib$?SupportsPrinterMib@CTcpMib@@UEAAHPEBD0KPEAH@Z"
    remap "__imp_?SnmpWalk@CTcpMib@@UEAAKPEBD0KPEAUAsnObjectIdentifier@@PEAUSnmpVarBindList@@@Z" "__imp_tcpmib$?SnmpWalk@CTcpMib@@UEAAKPEBD0KPEAUAsnObjectIdentifier@@PEAUSnmpVarBindList@@@Z"
    remap "__imp_?SnmpWalk@CTcpMib@@QEAAKPEBD0KPEAUSnmpVarBindList@@@Z" "__imp_tcpmib$?SnmpWalk@CTcpMib@@QEAAKPEBD0KPEAUSnmpVarBindList@@@Z"
    remap "__imp_?SnmpGetNext@CTcpMib@@UEAAKPEBD0KPEAUAsnObjectIdentifier@@PEAUSnmpVarBindList@@@Z" "__imp_tcpmib$?SnmpGetNext@CTcpMib@@UEAAKPEBD0KPEAUAsnObjectIdentifier@@PEAUSnmpVarBindList@@@Z"
    remap "__imp_?SnmpGetNext@CTcpMib@@QEAAKPEBD0KPEAUSnmpVarBindList@@@Z" "__imp_tcpmib$?SnmpGetNext@CTcpMib@@QEAAKPEBD0KPEAUSnmpVarBindList@@@Z"
    remap "__imp_?SnmpGet@CTcpMib@@UEAAKPEBD0KPEAUAsnObjectIdentifier@@PEAUSnmpVarBindList@@@Z" "__imp_tcpmib$?SnmpGet@CTcpMib@@UEAAKPEBD0KPEAUAsnObjectIdentifier@@PEAUSnmpVarBindList@@@Z"
    remap "__imp_?SnmpGet@CTcpMib@@QEAAKPEBD0KPEAUSnmpVarBindList@@@Z" "__imp_tcpmib$?SnmpGet@CTcpMib@@QEAAKPEBD0KPEAUSnmpVarBindList@@@Z"
    remap "__imp_?SnmpCallback@CTcpMib@@CAKPEAX0I_K_J0@Z" "__imp_tcpmib$?SnmpCallback@CTcpMib@@CAKPEAX0I_K_J0@Z"
    remap "__imp_?RequestDeviceStatus@CTcpMib@@UEAAKPEAXKPEBG1K@Z" "__imp_tcpmib$?RequestDeviceStatus@CTcpMib@@UEAAKPEAXKPEBG1K@Z"
    remap "__imp_?RegisterDeviceStatusCallback@CTcpMib@@UEAAKP6AKHPEBD0KKK@ZPEAPEAX@Z" "__imp_tcpmib$?RegisterDeviceStatusCallback@CTcpMib@@UEAAKP6AKHPEBD0KKK@ZPEAPEAX@Z"
    remap "__imp_?MapAsynchToPortStatus@CTcpMib@@CAHKPEAU_PORT_INFO_3W@@@Z" "__imp_tcpmib$?MapAsynchToPortStatus@CTcpMib@@CAHKPEAU_PORT_INFO_3W@@@Z"
    remap "__imp_?IsValid@CTcpMib@@QEBAHXZ" "__imp_tcpmib$?IsValid@CTcpMib@@QEBAHXZ"
    remap "__imp_?InitSnmp@CTcpMib@@UEAAKXZ" "__imp_tcpmib$?InitSnmp@CTcpMib@@UEAAKXZ"
    remap "__imp_?GetStatusFromVBL@CTcpMib@@CAKPEAXPEAUsmiVALUE@@11@Z" "__imp_tcpmib$?GetStatusFromVBL@CTcpMib@@CAKPEAXPEAUsmiVALUE@@11@Z"
    remap "__imp_?GetNextRequestId@CTcpMib@@UEAAKPEAK@Z" "__imp_tcpmib$?GetNextRequestId@CTcpMib@@UEAAKPEAK@Z"
    remap "__imp_?GetDeviceName@CTcpMib@@UEAAKPEBD0KKPEAG@Z" "__imp_tcpmib$?GetDeviceName@CTcpMib@@UEAAKPEBD0KKPEAG@Z"
    remap "__imp_?GetDeviceHWAddress@CTcpMib@@UEAAKPEBD0KKPEAG@Z" "__imp_tcpmib$?GetDeviceHWAddress@CTcpMib@@UEAAKPEBD0KKPEAG@Z"
    remap "__imp_?GetDeviceDescription@CTcpMib@@UEAAKPEBD0KPEAGK@Z" "__imp_tcpmib$?GetDeviceDescription@CTcpMib@@UEAAKPEBD0KPEAGK@Z"
    remap "__imp_?ExitCSection@CTcpMib@@AEAAXXZ" "__imp_tcpmib$?ExitCSection@CTcpMib@@AEAAXXZ"
    remap "__imp_?EnterCSection@CTcpMib@@AEAAXXZ" "__imp_tcpmib$?EnterCSection@CTcpMib@@AEAAXXZ"
    remap "__imp_??_7CTcpMibABC@@6B@" "__imp_tcpmib$??_7CTcpMibABC@@6B@"
    remap "__imp_??_7CTcpMib@@6B@" "__imp_tcpmib$??_7CTcpMib@@6B@"
    remap "__imp_??4CTcpMibABC@@QEAAAEAV0@AEBV0@@Z" "__imp_tcpmib$??4CTcpMibABC@@QEAAAEAV0@AEBV0@@Z"
    remap "__imp_??4CTcpMib@@QEAAAEAV0@AEBV0@@Z" "__imp_tcpmib$??4CTcpMib@@QEAAAEAV0@AEBV0@@Z"
    remap "__imp_??1CTcpMibABC@@UEAA@XZ" "__imp_tcpmib$??1CTcpMibABC@@UEAA@XZ"
    remap "__imp_??1CTcpMib@@UEAA@XZ" "__imp_tcpmib$??1CTcpMib@@UEAA@XZ"
    remap "__imp_??0CTcpMibABC@@QEAA@XZ" "__imp_tcpmib$??0CTcpMibABC@@QEAA@XZ"
    remap "__imp_??0CTcpMibABC@@QEAA@AEBV0@@Z" "__imp_tcpmib$??0CTcpMibABC@@QEAA@AEBV0@@Z"
    remap "__imp_??0CTcpMib@@QEAA@XZ" "__imp_tcpmib$??0CTcpMib@@QEAA@XZ"
    remap "__imp_??0CTcpMib@@QEAA@AEBV0@@Z" "__imp_tcpmib$??0CTcpMib@@QEAA@AEBV0@@Z"
x86:
