# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_URLAssociationDialogW" "__imp_url$URLAssociationDialogW"
    remap "__imp_URLAssociationDialogA" "__imp_url$URLAssociationDialogA"
    remap "__imp_TranslateURLW" "__imp_url$TranslateURLW"
    remap "__imp_TranslateURLA" "__imp_url$TranslateURLA"
    remap "__imp_TelnetProtocolHandlerA" "__imp_url$TelnetProtocolHandlerA"
    remap "__imp_TelnetProtocolHandler" "__imp_url$TelnetProtocolHandler"
    remap "__imp_OpenURLA" "__imp_url$OpenURLA"
    remap "__imp_OpenURL" "__imp_url$OpenURL"
    remap "__imp_NewsProtocolHandlerA" "__imp_url$NewsProtocolHandlerA"
    remap "__imp_NewsProtocolHandler" "__imp_url$NewsProtocolHandler"
    remap "__imp_MailToProtocolHandlerA" "__imp_url$MailToProtocolHandlerA"
    remap "__imp_MailToProtocolHandler" "__imp_url$MailToProtocolHandler"
    remap "__imp_MIMEAssociationDialogW" "__imp_url$MIMEAssociationDialogW"
    remap "__imp_MIMEAssociationDialogA" "__imp_url$MIMEAssociationDialogA"
    remap "__imp_InetIsOffline" "__imp_url$InetIsOffline"
    remap "__imp_FileProtocolHandlerA" "__imp_url$FileProtocolHandlerA"
    remap "__imp_FileProtocolHandler" "__imp_url$FileProtocolHandler"
    remap "__imp_DllGetClassObject" "__imp_url$DllGetClassObject"
    remap "__imp_DllCanUnloadNow" "__imp_url$DllCanUnloadNow"
    remap "__imp_AutodialHookCallback" "__imp_url$AutodialHookCallback"
    remap "__imp_AddMIMEFileTypesPS" "__imp_url$AddMIMEFileTypesPS"
x86:
    remap "__imp__URLAssociationDialogW@24" "__imp__url$URLAssociationDialogW@24"
    remap "__imp__URLAssociationDialogA@24" "__imp__url$URLAssociationDialogA@24"
    remap "__imp__TranslateURLW@12" "__imp__url$TranslateURLW@12"
    remap "__imp__TranslateURLA@12" "__imp__url$TranslateURLA@12"
    remap "__imp__MIMEAssociationDialogW@24" "__imp__url$MIMEAssociationDialogW@24"
    remap "__imp__MIMEAssociationDialogA@24" "__imp__url$MIMEAssociationDialogA@24"
    remap "__imp__InetIsOffline@4" "__imp__url$InetIsOffline@4"
