# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_VerQueryValueW" "__imp_version$VerQueryValueW"
    remap "__imp_VerQueryValueIndexW" "__imp_version$VerQueryValueIndexW"
    remap "__imp_VerQueryValueIndexA" "__imp_version$VerQueryValueIndexA"
    remap "__imp_VerQueryValueA" "__imp_version$VerQueryValueA"
    remap "__imp_VerLanguageNameW" "__imp_version$VerLanguageNameW"
    remap "__imp_VerLanguageNameA" "__imp_version$VerLanguageNameA"
    remap "__imp_VerInstallFileW" "__imp_version$VerInstallFileW"
    remap "__imp_VerInstallFileA" "__imp_version$VerInstallFileA"
    remap "__imp_VerFindFileW" "__imp_version$VerFindFileW"
    remap "__imp_VerFindFileA" "__imp_version$VerFindFileA"
    remap "__imp_GetFileVersionInfoW" "__imp_version$GetFileVersionInfoW"
    remap "__imp_GetFileVersionInfoSizeW" "__imp_version$GetFileVersionInfoSizeW"
    remap "__imp_GetFileVersionInfoSizeExW" "__imp_version$GetFileVersionInfoSizeExW"
    remap "__imp_GetFileVersionInfoSizeExA" "__imp_version$GetFileVersionInfoSizeExA"
    remap "__imp_GetFileVersionInfoSizeA" "__imp_version$GetFileVersionInfoSizeA"
    remap "__imp_GetFileVersionInfoExW" "__imp_version$GetFileVersionInfoExW"
    remap "__imp_GetFileVersionInfoExA" "__imp_version$GetFileVersionInfoExA"
    remap "__imp_GetFileVersionInfoByHandle" "__imp_version$GetFileVersionInfoByHandle"
    remap "__imp_GetFileVersionInfoA" "__imp_version$GetFileVersionInfoA"
x86:
    remap "__imp__VerQueryValueW@16" "__imp__version$VerQueryValueW@16"
    remap "__imp__VerQueryValueIndexW@24" "__imp__version$VerQueryValueIndexW@24"
    remap "__imp__VerQueryValueIndexA@24" "__imp__version$VerQueryValueIndexA@24"
    remap "__imp__VerQueryValueA@16" "__imp__version$VerQueryValueA@16"
    remap "__imp__VerLanguageNameW@12" "__imp__version$VerLanguageNameW@12"
    remap "__imp__VerLanguageNameA@12" "__imp__version$VerLanguageNameA@12"
    remap "__imp__VerInstallFileW@32" "__imp__version$VerInstallFileW@32"
    remap "__imp__VerInstallFileA@32" "__imp__version$VerInstallFileA@32"
    remap "__imp__VerFindFileW@32" "__imp__version$VerFindFileW@32"
    remap "__imp__VerFindFileA@32" "__imp__version$VerFindFileA@32"
    remap "__imp__GetFileVersionInfoW@16" "__imp__version$GetFileVersionInfoW@16"
    remap "__imp__GetFileVersionInfoSizeW@8" "__imp__version$GetFileVersionInfoSizeW@8"
    remap "__imp__GetFileVersionInfoSizeA@8" "__imp__version$GetFileVersionInfoSizeA@8"
    remap "__imp__GetFileVersionInfoA@16" "__imp__version$GetFileVersionInfoA@16"
