# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_VerifierStopMessage" "__imp_verifier$VerifierStopMessage"
    remap "__imp_VerifierSetRuntimeFlags" "__imp_verifier$VerifierSetRuntimeFlags"
    remap "__imp_VerifierSetFlags" "__imp_verifier$VerifierSetFlags"
    remap "__imp_VerifierSetFaultInjectionProbability" "__imp_verifier$VerifierSetFaultInjectionProbability"
    remap "__imp_VerifierQueryRuntimeFlags" "__imp_verifier$VerifierQueryRuntimeFlags"
    remap "__imp_VerifierLogMessage" "__imp_verifier$VerifierLogMessage"
    remap "__imp_VerifierIsDllEntryActive" "__imp_verifier$VerifierIsDllEntryActive"
    remap "__imp_VerifierIsCurrentThreadHoldingLocks" "__imp_verifier$VerifierIsCurrentThreadHoldingLocks"
    remap "__imp_VerifierEnumerateResource" "__imp_verifier$VerifierEnumerateResource"
    remap "__imp_VerifierEnableFaultInjectionTargetRange" "__imp_verifier$VerifierEnableFaultInjectionTargetRange"
    remap "__imp_VerifierEnableFaultInjectionExclusionRange" "__imp_verifier$VerifierEnableFaultInjectionExclusionRange"
    remap "__imp_VerifierDisableFaultInjectionTargetRange" "__imp_verifier$VerifierDisableFaultInjectionTargetRange"
    remap "__imp_VerifierDisableFaultInjectionExclusionRange" "__imp_verifier$VerifierDisableFaultInjectionExclusionRange"
    remap "__imp_VerifierDestroyRpcPageHeap" "__imp_verifier$VerifierDestroyRpcPageHeap"
    remap "__imp_VerifierDeleteFreeMemoryCallback" "__imp_verifier$VerifierDeleteFreeMemoryCallback"
    remap "__imp_VerifierCreateRpcPageHeap" "__imp_verifier$VerifierCreateRpcPageHeap"
    remap "__imp_VerifierAddFreeMemoryCallback" "__imp_verifier$VerifierAddFreeMemoryCallback"
x86:
