# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_InstallEULA" "__imp_winbrand$InstallEULA"
    remap "__imp_GetInstalledEULAPath" "__imp_winbrand$GetInstalledEULAPath"
    remap "__imp_GetHinstanceByNameSpace" "__imp_winbrand$GetHinstanceByNameSpace"
    remap "__imp_GetEULAInCurrentUILanguage" "__imp_winbrand$GetEULAInCurrentUILanguage"
    remap "__imp_GetEULAFileEx" "__imp_winbrand$GetEULAFileEx"
    remap "__imp_GetEULAFile" "__imp_winbrand$GetEULAFile"
    remap "__imp_EulaFreeBuffer" "__imp_winbrand$EulaFreeBuffer"
    remap "__imp_BrandingLoadStringForEdition" "__imp_winbrand$BrandingLoadStringForEdition"
    remap "__imp_BrandingLoadString" "__imp_winbrand$BrandingLoadString"
    remap "__imp_BrandingLoadNeutralStringForEdition" "__imp_winbrand$BrandingLoadNeutralStringForEdition"
    remap "__imp_BrandingLoadImage" "__imp_winbrand$BrandingLoadImage"
    remap "__imp_BrandingLoadIcon" "__imp_winbrand$BrandingLoadIcon"
    remap "__imp_BrandingLoadCursor" "__imp_winbrand$BrandingLoadCursor"
    remap "__imp_BrandingLoadBitmap" "__imp_winbrand$BrandingLoadBitmap"
    remap "__imp_BrandingFormatStringForEdition" "__imp_winbrand$BrandingFormatStringForEdition"
    remap "__imp_BrandingFormatString" "__imp_winbrand$BrandingFormatString"
x86:
    remap "__imp__InstallEULA@16" "__imp__winbrand$InstallEULA@16"
    remap "__imp__GetInstalledEULAPath@4" "__imp__winbrand$GetInstalledEULAPath@4"
    remap "__imp__GetHinstanceByNameSpace@4" "__imp__winbrand$GetHinstanceByNameSpace@4"
    remap "__imp__GetEULAInCurrentUILanguage@4" "__imp__winbrand$GetEULAInCurrentUILanguage@4"
    remap "__imp__GetEULAFileEx@24" "__imp__winbrand$GetEULAFileEx@24"
    remap "__imp__GetEULAFile@20" "__imp__winbrand$GetEULAFile@20"
    remap "__imp__EulaFreeBuffer@4" "__imp__winbrand$EulaFreeBuffer@4"
    remap "__imp__BrandingLoadStringForEdition@24" "__imp__winbrand$BrandingLoadStringForEdition@24"
    remap "__imp__BrandingLoadString@16" "__imp__winbrand$BrandingLoadString@16"
    remap "__imp__BrandingLoadNeutralStringForEdition@20" "__imp__winbrand$BrandingLoadNeutralStringForEdition@20"
    remap "__imp__BrandingLoadImage@24" "__imp__winbrand$BrandingLoadImage@24"
    remap "__imp__BrandingLoadIcon@8" "__imp__winbrand$BrandingLoadIcon@8"
    remap "__imp__BrandingLoadCursor@8" "__imp__winbrand$BrandingLoadCursor@8"
    remap "__imp__BrandingLoadBitmap@8" "__imp__winbrand$BrandingLoadBitmap@8"
    remap "__imp__BrandingFormatStringForEdition@12" "__imp__winbrand$BrandingFormatStringForEdition@12"
    remap "__imp__BrandingFormatString@4" "__imp__winbrand$BrandingFormatString@4"
