x64:
    remap "__imp_WSHStringToAddress" "__imp_wshbth$WSHStringToAddress"
    remap "__imp_WSHSetSocketInformation" "__imp_wshbth$WSHSetSocketInformation"
    remap "__imp_WSHOpenSocket2" "__imp_wshbth$WSHOpenSocket2"
    remap "__imp_WSHOpenSocket" "__imp_wshbth$WSHOpenSocket"
    remap "__imp_WSHNotify" "__imp_wshbth$WSHNotify"
    remap "__imp_WSHJoinLeaf" "__imp_wshbth$WSHJoinLeaf"
    remap "__imp_WSHIoctl" "__imp_wshbth$WSHIoctl"
    remap "__imp_WSHGetWinsockMapping" "__imp_wshbth$WSHGetWinsockMapping"
    remap "__imp_WSHGetWildcardSockaddr" "__imp_wshbth$WSHGetWildcardSockaddr"
    remap "__imp_WSHGetWSAProtocolInfo" "__imp_wshbth$WSHGetWSAProtocolInfo"
    remap "__imp_WSHGetSocketInformation" "__imp_wshbth$WSHGetSocketInformation"
    remap "__imp_WSHGetSockaddrType" "__imp_wshbth$WSHGetSockaddrType"
    remap "__imp_WSHGetProviderGuid" "__imp_wshbth$WSHGetProviderGuid"
    remap "__imp_WSHGetBroadcastSockaddr" "__imp_wshbth$WSHGetBroadcastSockaddr"
    remap "__imp_WSHEnumProtocols" "__imp_wshbth$WSHEnumProtocols"
    remap "__imp_WSHAddressToString" "__imp_wshbth$WSHAddressToString"
    remap "__imp_NSPStartup" "__imp_wshbth$NSPStartup"
x86:
