x64:
    remap "__imp_UnloadImportDS" "__imp_wiadss$UnloadImportDS"
    remap "__imp_LoadImportDS" "__imp_wiadss$LoadImportDS"
    remap "__imp_GetLoaderStatus" "__imp_wiadss$GetLoaderStatus"
    remap "__imp_FindNextImportDS" "__imp_wiadss$FindNextImportDS"
    remap "__imp_FindImportDSByDeviceName" "__imp_wiadss$FindImportDSByDeviceName"
    remap "__imp_FindFirstImportDS" "__imp_wiadss$FindFirstImportDS"
    remap "__imp_CloseFindContext" "__imp_wiadss$CloseFindContext"
    remap "__imp_?SetUsed@BUFFER_CHAIN_ITEM@@QEAAXK@Z" "__imp_wiadss$?SetUsed@BUFFER_CHAIN_ITEM@@QEAAXK@Z"
    remap "__imp_?QueryUsed@BUFFER_CHAIN_ITEM@@QEBAKXZ" "__imp_wiadss$?QueryUsed@BUFFER_CHAIN_ITEM@@QEBAKXZ"
    remap "__imp_?QuerySize@BUFFER@@QEBAIXZ" "__imp_wiadss$?QuerySize@BUFFER@@QEBAIXZ"
    remap "__imp_?QueryPtr@BUFFER@@QEBAPEAXXZ" "__imp_wiadss$?QueryPtr@BUFFER@@QEBAPEAXXZ"
    remap "__imp_??_FBUFFER_CHAIN_ITEM@@QEAAXXZ" "__imp_wiadss$??_FBUFFER_CHAIN_ITEM@@QEAAXXZ"
    remap "__imp_??_FBUFFER@@QEAAXXZ" "__imp_wiadss$??_FBUFFER@@QEAAXXZ"
    remap "__imp_??1BUFFER_CHAIN_ITEM@@QEAA@XZ" "__imp_wiadss$??1BUFFER_CHAIN_ITEM@@QEAA@XZ"
    remap "__imp_??1BUFFER_CHAIN@@QEAA@XZ" "__imp_wiadss$??1BUFFER_CHAIN@@QEAA@XZ"
    remap "__imp_??1BUFFER@@QEAA@XZ" "__imp_wiadss$??1BUFFER@@QEAA@XZ"
    remap "__imp_??0BUFFER_CHAIN_ITEM@@QEAA@I@Z" "__imp_wiadss$??0BUFFER_CHAIN_ITEM@@QEAA@I@Z"
    remap "__imp_??0BUFFER_CHAIN@@QEAA@XZ" "__imp_wiadss$??0BUFFER_CHAIN@@QEAA@XZ"
    remap "__imp_??0BUFFER@@QEAA@I@Z" "__imp_wiadss$??0BUFFER@@QEAA@I@Z"
x86:
    remap "__imp__UnloadImportDS@4" "__imp__wiadss$UnloadImportDS@4"
    remap "__imp__LoadImportDS@16" "__imp__wiadss$LoadImportDS@16"
    remap "__imp__GetLoaderStatus@4" "__imp__wiadss$GetLoaderStatus@4"
    remap "__imp__FindNextImportDS@8" "__imp__wiadss$FindNextImportDS@8"
    remap "__imp__FindImportDSByDeviceName@8" "__imp__wiadss$FindImportDSByDeviceName@8"
    remap "__imp__FindFirstImportDS@8" "__imp__wiadss$FindFirstImportDS@8"
    remap "__imp__CloseFindContext@4" "__imp__wiadss$CloseFindContext@4"
