# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_WahWriteLSPEvent" "__imp_ws2help$WahWriteLSPEvent"
    remap "__imp_WahWaitForNotification" "__imp_ws2help$WahWaitForNotification"
    remap "__imp_WahRemoveHandleContext" "__imp_ws2help$WahRemoveHandleContext"
    remap "__imp_WahReferenceContextByHandle" "__imp_ws2help$WahReferenceContextByHandle"
    remap "__imp_WahQueueUserApc" "__imp_ws2help$WahQueueUserApc"
    remap "__imp_WahOpenNotificationHandleHelper" "__imp_ws2help$WahOpenNotificationHandleHelper"
    remap "__imp_WahOpenHandleHelper" "__imp_ws2help$WahOpenHandleHelper"
    remap "__imp_WahOpenCurrentThread" "__imp_ws2help$WahOpenCurrentThread"
    remap "__imp_WahOpenApcHelper" "__imp_ws2help$WahOpenApcHelper"
    remap "__imp_WahNotifyAllProcesses" "__imp_ws2help$WahNotifyAllProcesses"
    remap "__imp_WahInsertHandleContext" "__imp_ws2help$WahInsertHandleContext"
    remap "__imp_WahEnumerateHandleContexts" "__imp_ws2help$WahEnumerateHandleContexts"
    remap "__imp_WahEnableNonIFSHandleSupport" "__imp_ws2help$WahEnableNonIFSHandleSupport"
    remap "__imp_WahDisableNonIFSHandleSupport" "__imp_ws2help$WahDisableNonIFSHandleSupport"
    remap "__imp_WahDestroyHandleContextTable" "__imp_ws2help$WahDestroyHandleContextTable"
    remap "__imp_WahCreateSocketHandle" "__imp_ws2help$WahCreateSocketHandle"
    remap "__imp_WahCreateNotificationHandle" "__imp_ws2help$WahCreateNotificationHandle"
    remap "__imp_WahCreateHandleContextTable" "__imp_ws2help$WahCreateHandleContextTable"
    remap "__imp_WahCompleteRequest" "__imp_ws2help$WahCompleteRequest"
    remap "__imp_WahCloseThread" "__imp_ws2help$WahCloseThread"
    remap "__imp_WahCloseSocketHandle" "__imp_ws2help$WahCloseSocketHandle"
    remap "__imp_WahCloseNotificationHandleHelper" "__imp_ws2help$WahCloseNotificationHandleHelper"
    remap "__imp_WahCloseHandleHelper" "__imp_ws2help$WahCloseHandleHelper"
    remap "__imp_WahCloseApcHelper" "__imp_ws2help$WahCloseApcHelper"
x86:
