x64:
    remap "__imp_WofWimUpdateEntry" "__imp_wofutil$WofWimUpdateEntry"
    remap "__imp_WofWimSuspendEntry" "__imp_wofutil$WofWimSuspendEntry"
    remap "__imp_WofWimRemoveEntry" "__imp_wofutil$WofWimRemoveEntry"
    remap "__imp_WofWimEnumFiles" "__imp_wofutil$WofWimEnumFiles"
    remap "__imp_WofWimAddEntry" "__imp_wofutil$WofWimAddEntry"
    remap "__imp_WofShouldCompressBinaries" "__imp_wofutil$WofShouldCompressBinaries"
    remap "__imp_WofSetFileDataLocation" "__imp_wofutil$WofSetFileDataLocation"
    remap "__imp_WofIsExternalFile" "__imp_wofutil$WofIsExternalFile"
    remap "__imp_WofGetDriverVersion" "__imp_wofutil$WofGetDriverVersion"
    remap "__imp_WofFileEnumFiles" "__imp_wofutil$WofFileEnumFiles"
    remap "__imp_WofEnumEntries" "__imp_wofutil$WofEnumEntries"
x86:
    remap "__imp__WofWimUpdateEntry@16" "__imp__wofutil$WofWimUpdateEntry@16"
    remap "__imp__WofWimSuspendEntry@12" "__imp__wofutil$WofWimSuspendEntry@12"
    remap "__imp__WofWimRemoveEntry@12" "__imp__wofutil$WofWimRemoveEntry@12"
    remap "__imp__WofWimEnumFiles@20" "__imp__wofutil$WofWimEnumFiles@20"
    remap "__imp__WofWimAddEntry@20" "__imp__wofutil$WofWimAddEntry@20"
    remap "__imp__WofShouldCompressBinaries@8" "__imp__wofutil$WofShouldCompressBinaries@8"
    remap "__imp__WofSetFileDataLocation@16" "__imp__wofutil$WofSetFileDataLocation@16"
    remap "__imp__WofIsExternalFile@20" "__imp__wofutil$WofIsExternalFile@20"
    remap "__imp__WofGetDriverVersion@12" "__imp__wofutil$WofGetDriverVersion@12"
    remap "__imp__WofFileEnumFiles@16" "__imp__wofutil$WofFileEnumFiles@16"
    remap "__imp__WofEnumEntries@16" "__imp__wofutil$WofEnumEntries@16"
