# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_WebSocketSend" "__imp_websocket$WebSocketSend"
    remap "__imp_WebSocketReceive" "__imp_websocket$WebSocketReceive"
    remap "__imp_WebSocketGetGlobalProperty" "__imp_websocket$WebSocketGetGlobalProperty"
    remap "__imp_WebSocketGetAction" "__imp_websocket$WebSocketGetAction"
    remap "__imp_WebSocketEndServerHandshake" "__imp_websocket$WebSocketEndServerHandshake"
    remap "__imp_WebSocketEndClientHandshake" "__imp_websocket$WebSocketEndClientHandshake"
    remap "__imp_WebSocketDeleteHandle" "__imp_websocket$WebSocketDeleteHandle"
    remap "__imp_WebSocketCreateServerHandle" "__imp_websocket$WebSocketCreateServerHandle"
    remap "__imp_WebSocketCreateClientHandle" "__imp_websocket$WebSocketCreateClientHandle"
    remap "__imp_WebSocketCompleteAction" "__imp_websocket$WebSocketCompleteAction"
    remap "__imp_WebSocketBeginServerHandshake" "__imp_websocket$WebSocketBeginServerHandshake"
    remap "__imp_WebSocketBeginClientHandshake" "__imp_websocket$WebSocketBeginClientHandshake"
    remap "__imp_WebSocketAbortHandle" "__imp_websocket$WebSocketAbortHandle"
x86:
    remap "__imp__WebSocketSend@16" "__imp__websocket$WebSocketSend@16"
    remap "__imp__WebSocketReceive@12" "__imp__websocket$WebSocketReceive@12"
    remap "__imp__WebSocketGetGlobalProperty@12" "__imp__websocket$WebSocketGetGlobalProperty@12"
    remap "__imp__WebSocketGetAction@32" "__imp__websocket$WebSocketGetAction@32"
    remap "__imp__WebSocketEndServerHandshake@4" "__imp__websocket$WebSocketEndServerHandshake@4"
    remap "__imp__WebSocketEndClientHandshake@24" "__imp__websocket$WebSocketEndClientHandshake@24"
    remap "__imp__WebSocketDeleteHandle@4" "__imp__websocket$WebSocketDeleteHandle@4"
    remap "__imp__WebSocketCreateServerHandle@12" "__imp__websocket$WebSocketCreateServerHandle@12"
    remap "__imp__WebSocketCreateClientHandle@12" "__imp__websocket$WebSocketCreateClientHandle@12"
    remap "__imp__WebSocketCompleteAction@12" "__imp__websocket$WebSocketCompleteAction@12"
    remap "__imp__WebSocketBeginServerHandshake@32" "__imp__websocket$WebSocketBeginServerHandshake@32"
    remap "__imp__WebSocketBeginClientHandshake@36" "__imp__websocket$WebSocketBeginClientHandshake@36"
    remap "__imp__WebSocketAbortHandle@4" "__imp__websocket$WebSocketAbortHandle@4"
