# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_fnW32TmSetServiceStatus" "__imp_w32time$fnW32TmSetServiceStatus"
    remap "__imp_fnW32TmRegisterServiceCtrlHandlerEx" "__imp_w32time$fnW32TmRegisterServiceCtrlHandlerEx"
    remap "__imp_fnW32TmI_ScSetServiceBits" "__imp_w32time$fnW32TmI_ScSetServiceBits"
    remap "__imp_W32TmServiceMain" "__imp_w32time$W32TmServiceMain"
    remap "__imp_W32TimeVerifyUnjoinConfig" "__imp_w32time$W32TimeVerifyUnjoinConfig"
    remap "__imp_W32TimeVerifyJoinConfig" "__imp_w32time$W32TimeVerifyJoinConfig"
    remap "__imp_W32TimeSyncNow" "__imp_w32time$W32TimeSyncNow"
    remap "__imp_W32TimeSetConfig" "__imp_w32time$W32TimeSetConfig"
    remap "__imp_W32TimeQueryStatus" "__imp_w32time$W32TimeQueryStatus"
    remap "__imp_W32TimeQuerySource" "__imp_w32time$W32TimeQuerySource"
    remap "__imp_W32TimeQueryNtpProviderConfiguration" "__imp_w32time$W32TimeQueryNtpProviderConfiguration"
    remap "__imp_W32TimeQueryNTPProviderStatus" "__imp_w32time$W32TimeQueryNTPProviderStatus"
    remap "__imp_W32TimeQueryHardwareProviderStatus" "__imp_w32time$W32TimeQueryHardwareProviderStatus"
    remap "__imp_W32TimeQueryConfiguration" "__imp_w32time$W32TimeQueryConfiguration"
    remap "__imp_W32TimeQueryConfig" "__imp_w32time$W32TimeQueryConfig"
    remap "__imp_W32TimeLog" "__imp_w32time$W32TimeLog"
    remap "__imp_W32TimeGetNetlogonServiceBits" "__imp_w32time$W32TimeGetNetlogonServiceBits"
    remap "__imp_W32TimeDeleteConfig" "__imp_w32time$W32TimeDeleteConfig"
    remap "__imp_W32TimeDcPromo" "__imp_w32time$W32TimeDcPromo"
    remap "__imp_W32TimeBufferFree" "__imp_w32time$W32TimeBufferFree"
    remap "__imp_TimeProvOpen" "__imp_w32time$TimeProvOpen"
    remap "__imp_TimeProvCommand" "__imp_w32time$TimeProvCommand"
    remap "__imp_TimeProvClose" "__imp_w32time$TimeProvClose"
    remap "__imp_SvchostPushServiceGlobals" "__imp_w32time$SvchostPushServiceGlobals"
    remap "__imp_SvchostEntry_W32Time" "__imp_w32time$SvchostEntry_W32Time"
x86:
