# Auto-generated DRF mapping (https://github.com/henkru/cp-dfr-defs)
x64:
    remap "__imp_TurboDispatchJumpAddressStart" "__imp_wow64cpu$TurboDispatchJumpAddressStart"
    remap "__imp_TurboDispatchJumpAddressEnd" "__imp_wow64cpu$TurboDispatchJumpAddressEnd"
    remap "__imp_CpuThreadTerm" "__imp_wow64cpu$CpuThreadTerm"
    remap "__imp_CpuThreadInit" "__imp_wow64cpu$CpuThreadInit"
    remap "__imp_CpuSuspendThread" "__imp_wow64cpu$CpuSuspendThread"
    remap "__imp_CpuSimulate" "__imp_wow64cpu$CpuSimulate"
    remap "__imp_CpuSetStackPointer" "__imp_wow64cpu$CpuSetStackPointer"
    remap "__imp_CpuSetInstructionPointer" "__imp_wow64cpu$CpuSetInstructionPointer"
    remap "__imp_CpuSetContext" "__imp_wow64cpu$CpuSetContext"
    remap "__imp_CpuResetToConsistentState" "__imp_wow64cpu$CpuResetToConsistentState"
    remap "__imp_CpuResetFloatingPoint" "__imp_wow64cpu$CpuResetFloatingPoint"
    remap "__imp_CpuProcessTerm" "__imp_wow64cpu$CpuProcessTerm"
    remap "__imp_CpuProcessInit" "__imp_wow64cpu$CpuProcessInit"
    remap "__imp_CpuProcessDebugEvent" "__imp_wow64cpu$CpuProcessDebugEvent"
    remap "__imp_CpuPrepareForDebuggerAttach" "__imp_wow64cpu$CpuPrepareForDebuggerAttach"
    remap "__imp_CpuNotifyDllUnload" "__imp_wow64cpu$CpuNotifyDllUnload"
    remap "__imp_CpuNotifyDllLoad" "__imp_wow64cpu$CpuNotifyDllLoad"
    remap "__imp_CpuInitializeStartupContext" "__imp_wow64cpu$CpuInitializeStartupContext"
    remap "__imp_CpuGetStackPointer" "__imp_wow64cpu$CpuGetStackPointer"
    remap "__imp_CpuGetContext" "__imp_wow64cpu$CpuGetContext"
    remap "__imp_CpuFlushInstructionCache" "__imp_wow64cpu$CpuFlushInstructionCache"
x86:
