x64:
    remap "__imp_XAudio2CreateWithVersionInfo" "__imp_xaudio2_9$XAudio2CreateWithVersionInfo"
    remap "__imp_XAudio2CreateWithSharedContexts" "__imp_xaudio2_9$XAudio2CreateWithSharedContexts"
    remap "__imp_XAudio2CreateV2_9" "__imp_xaudio2_9$XAudio2CreateV2_9"
    remap "__imp_XAudio2Create" "__imp_xaudio2_9$XAudio2Create"
    remap "__imp_X3DAudioInitialize" "__imp_xaudio2_9$X3DAudioInitialize"
    remap "__imp_X3DAudioCalculate" "__imp_xaudio2_9$X3DAudioCalculate"
    remap "__imp_CreateFX" "__imp_xaudio2_9$CreateFX"
    remap "__imp_CreateAudioVolumeMeter" "__imp_xaudio2_9$CreateAudioVolumeMeter"
    remap "__imp_CreateAudioReverbV2_8" "__imp_xaudio2_9$CreateAudioReverbV2_8"
    remap "__imp_CreateAudioReverb" "__imp_xaudio2_9$CreateAudioReverb"
x86:
    remap "__imp__XAudio2CreateWithVersionInfo@16" "__imp__xaudio2_9$XAudio2CreateWithVersionInfo@16"
    remap "__imp__XAudio2CreateWithSharedContexts@16" "__imp__xaudio2_9$XAudio2CreateWithSharedContexts@16"
    remap "__imp__XAudio2CreateV2_9@12" "__imp__xaudio2_9$XAudio2CreateV2_9@12"
    remap "__imp__XAudio2Create@12" "__imp__xaudio2_9$XAudio2Create@12"
    remap "__imp__X3DAudioInitialize" "__imp__xaudio2_9$X3DAudioInitialize"
    remap "__imp__X3DAudioCalculate" "__imp__xaudio2_9$X3DAudioCalculate"
    remap "__imp__CreateFX@0" "__imp__xaudio2_9$CreateFX@0"
    remap "__imp__CreateAudioVolumeMeter@4" "__imp__xaudio2_9$CreateAudioVolumeMeter@4"
    remap "__imp__CreateAudioReverbV2_8@4" "__imp__xaudio2_9$CreateAudioReverbV2_8@4"
    remap "__imp__CreateAudioReverb@4" "__imp__xaudio2_9$CreateAudioReverb@4"
